### ISSUE TITLE
alternative to transaction.newTypes

### ISSUE THREAD

**Issue by calibr** [yjs/yjs#158]
In the earlier version there was attribute `newTypes` in Transaction objects, but it's gone in the latest version. Is there any altenative solution that helps to get structures that have got created/updated in a transaction? I tried looking into `writeStructsFromTransaction`, but it seems that some functions that it needs are not exported from Yjs(`findIndexSS`).

**Comment by dmonad** [comment]
I'm hesitant to make this API public because I may want to change it in the future. What is your use-case for `newTypes`?

Something you can do is 

```js
Y.iterateStructs(transaction, doc.store.users.get(clientid), clockStart, len, struct => { .. })
```

Where `iterateStructs` is not yet exported. You could get the range of added structs from computing the difference between`transaction.beforeState` and `transaction.afterState`. But I'm not sure if it even makes sense to expose this.

Alternatively, what do you think about adding a new method `transaction.iterateNewStructs(struct => {})` to the Transaction object?

**Comment by calibr** [comment]
In our documents we have user mention objects, they are stored as embeds in deltas and thus are ItemEmbeds. On the server side I used `newTypes` to detect new ItemEmbeds types and do needed action as soon as new mention appears.

>Alternatively, what do you think about adding a new method transaction.iterateNewStructs(struct => {}) to the Transaction object?

Yes, sure it will be good to have such a method if this method will return the same structs/types as `newTypes` would have.

**Comment by dmonad** [comment]
Makes sense. I will add this feature this week.

**Comment by dmonad** [comment]
Completely forgot to mention that all events now implement a `event.changes.added` and `event.changes.removed` property that defines the added/removed elements. It is a computed property.

Just iterating over new structs, like I suggested, might be error-prone because in some cases a struct has been added and then removed in the same transaction. 

YEvent now implements `event.changes` with an easy description of what changed.

```js
event.changes.added // set of added structs that were not deleted by the same transaction
event.changes.deleted // set of deleted structs that were not added in the same transaction
```

It also computes the changes in the delta format. I feel pretty good about the API, so I might put it in the docs soon. Please let me know what you think.

**Comment by calibr** [comment]
@dmonad I will check that out, thanks !
