### ISSUE TITLE
restoring document to a specific state

### ISSUE THREAD

**Issue by calibr** [yjs/yjs#159]
I see that new yjs is coming with Snapshots, will they be able to restore the whole document to a specific state based on StateSet and DeleteSet ?

What I did in the earlier version was essentialy packing the document into a syncStep2 message to specific state and then feeding this message to a new document.

```
function backDocToState(doc, state) {
  const { ss, ds } = state
  const needState = new Map<number, number>(ss)
  const encoder = encoding.createEncoder()
  encoding.writeVarUint(encoder, syncProtocol.messageYjsSyncStep2)
  const lenPos = encoding.length(encoder)
  encoding.writeUint32(encoder, 0)
  let len = 0
  const tempStructs = []
  for (let user of needState.keys()) {
    let clock = needState.get(user) || 0
    if (user !== ID.RootFakeUserID) {
      const minBound = ID.createID(user, 0)
      doc.os.iterate(minBound, ID.createID(user, clock - 1), struct => {
        tempStructs.push(struct._id, struct._length, struct._content)
        if((struct._id.clock + struct._length - 1) > clock) {
          const lenDif = struct._id.clock + struct._length - clock - 1
          struct._splitAt(doc, lenDif)
        }
        struct._toBinary(encoder)
        len++
      })
    }
  }
  encoding.setUint32(encoder, lenPos, len)

  const tmpDeleteStore = new Y.DeleteStore()
  for(let [userId, clock, length] of ds) {
    tmpDeleteStore.mark(ID.createID(userId, clock), length)
  }

  Y.writeDeleteStore(encoder, tmpDeleteStore)

  const buf = encoding.toBuffer(encoder)
  const decoder = decoding.createDecoder(buf)

  const newDoc = new Y.Y()
  newDoc.transact(() => {
    syncProtocol.readSyncMessage(decoder, encoding.createEncoder(), newDoc)
  })
}
```

Probably I can do the same in the current version of yjs, but I will be happy to use something easier and more robust than this if yjs core functions allow that.

**Comment by dmonad** [comment]
I like the idea of your approach. If this works for you, you should definitely use it. At some point you could switch to the Yjs based snapshotting approach. 

As you said, Snapshots in Yjs are based on StateSet and DeleteSet. Ideally, you can view an old state of the data without recreating a separate Yjs instance (which is not too bad tbh). But I also want to be able to show the differences between two snapshots. I'm currently working on this for a ProseMirror based project. The y-prosemirror binding will iterate over the shared types using functions like `typeListToArraySnapshot` instead of the `toArray` method. But at some point, I want to be able to have a view on the data. The view will just look like the `Y` instance and support all types, but none of the write methods.

**Comment by zlv-thisF** [comment]
hey, i am interested in this topic.

seems can restore document by code below
```
// save
  const state = Y.encodeStateAsUpdate(ydoc-now)  // then save-in-db
```
```
// restore
Y.applyUpdate(emptyYdoc, state-from-db)
```

besides, i need Y.snapshot to show the differences, so i need save snapshot to db as well. so my question is: is there anyway to integrate Y.shapshot's snapshot with Y.encodeStateAsUpdate's state ?  or can i restore document directly from snapshot rather than state by encodeStateAsUpdate ?

**Comment by dmonad** [comment]
> is there anyway to integrate Y.shapshot's snapshot with Y.encodeStateAsUpdate's state

So you want to encode these into a single Uint8Array? You could encode these yourself. E.g using [lib0/encoding](https://github.com/dmonad/lib0#readme)j

**Comment by calibr** [comment]
@dmonad WDYT do we need to implement `function backDocToState(doc, state)` with snapshots or separately? With snapshots it could look like: `function createDocFromSnapshot(baseDoc, snapshot): Y.Doc`

**Comment by dmonad** [comment]
`createDocFromSnapshot` might be the way to go.

**Comment by bkempe** [comment]
@dmonad For a `YText` and using the callback mechanism in https://github.com/yjs/y-websocket/blob/master/bin/callback.js to store a document, is `yText.toDelta()` and yText.applyDelta(...)` also a viable approach to store/restore an "archived" document into leveldb?
Can you elaborate on the differences to snapshots (except of course that toDelta is not available for other types)?

**Comment by tommoor** [comment]
> `createDocFromSnapshot` might be the way to go.

I'm not sure it's able to perform the usecase here, `createDocFromSnapshot` will produce a new document at the snapshot state – but if you want to take the existing document and create an update that reverts it to the snapshot (like a git revert that still moves history forward) I'm not finding any possible way to do that with the existing API's?

**Comment by abhinavdayal** [comment]
When I try to use crrateDocFromSnapshot, I get following error

```
const snap = Y.decodeSnapshot(snapshot);
const doc = Y.createDocFromSnapshot(ydoc, snap)
Error fetching sources for document Error: originDoc must not be garbage collected
```
`ydoc` above is the current document, snapshot is the previous instance of the same document.

**Comment by dmonad** [comment]
Closing because the feature has already been implemented.
