### ISSUE TITLE
Share more than one doc with only one connection?

### ISSUE THREAD

**Issue by chlec** [yjs/yjs#167]
I started using Yjs recently on my project, and I wanted to know if it's possible to share more than one doc with only one WebSocket connection? I already checked the source code of different Yjs packages but I didn't find anything that could handle that. So is there a way? Or I need to try to implement this feature by myself?

Thanks!

**Comment by calibr** [comment]
@chlec I believe this is possible to implement, but you will need to modify the websocket server and the websocket client libraries to make this work, because right now it is just one doc per connection

server: https://github.com/yjs/y-websocket/blob/master/bin/utils.js
client: https://github.com/yjs/y-websocket/blob/master/src/y-websocket.js
