### ISSUE TITLE
How do you persist data in v13?

### ISSUE THREAD

**Issue by CyriacBr** [yjs/yjs#170]
Using y-websocket, is there any way to get the merged model before it is sent to the clients? Or even a way to populate the clients directly?
My goal is to persist the models on the database of my app (MySQL).

It looks like y-websocket supports persisting data with `leveldb` already. However, it's actually not working. From `y-websocket/bin/utils.js`:
`const LevelDbPersistence = require('y-leveldb').LevelDbPersistence`
But `leveldb` doesn't have any `LevelDbPersistence` export.

Is it something still being worked-on?

**Comment by dmonad** [comment]
Hi @CyriacBr,

Some time ago I was working on leveldb persistence and you found an unstable reminiscent. But there are no official database adapters yet for v13.

The Yjs encoding approach has simple API documented here: https://github.com/yjs/yjs#document-updates. I consider the API stable for the stable release of v13. With this, you can build your own custom MySQL database adapter. If you want to use y-websocket with a custom persistence layer, I could expose the Yjs document so you can have access to the document updates.

Eventually, I want to port y-leveldb properly to v13 - but there is still a lot of more important stuff to do.

**Comment by CyriacBr** [comment]
@dmonad Thanks for the quick reply!

> If you want to use y-websocket with a custom persistence layer, I could expose the Yjs document so you can have access to the document updates.

Yes that'd be a better approach I think. I'm using `y-monaco` alongside `y-websocket` and the rooms contain specific IDs that my backend can recognize. I'd then just need to retrieve the updated documents and save them to a specific table according to the IDs.
I've tried to examine `y-websocket`'s [https://github.com/yjs/y-websocket/blob/master/bin/utils.js](sources) but I am a bit lost on how to retrieve the update.
I'd appreciate any pointer.

**Comment by calibr** [comment]
@CyriacBr in my project I use leveldb with yjs 13, if you still need it you can find it here https://gist.github.com/calibr/c8764d796db270c7c60460f254451580

it is working fine for me so far

**Comment by dmonad** [comment]
Thanks for sharing that @calibr! @CyriacBr, you should definitely have a look at the above example. It generates a unique key for each update. Then you can iterate over all update messages and recreate the document.

FYI @calibr, you could also use `performance.now()` instead of `Date.now()`. By spec, the former must always increase with each call.

The example above also uses the sync-protocol to generate update messages (which is absolutely fine). But you could also use only the new API functions from the `yjs` repository to encode update messages.

I just publish `y-websocket@1.0.5` that allows you to define a custom persistence adapter. Complete example:

```js
#!/usr/bin/env node

/**
 * @type {any}
 */
const WebSocket = require('ws')
const http = require('http')
const wss = new WebSocket.Server({ noServer: true })
const utils = require('y-websocket/bin/utils.js')
const setupWSConnection = utils.setupWSConnection

const port = process.env.PORT || 1234

const server = http.createServer((request, response) => {
  response.writeHead(200, { 'Content-Type': 'text/plain' })
  response.end('okay')
})

/*
 Persistence must have the following signature:
{ bindState: function(string,WSSharedDoc):void, writeState:function(string,WSSharedDoc):Promise }
*/
utils.setPersistence({
  bindState: (documentName, doc) => {
    // Here you listen to granular document updates and store them in the database
    // You don't have to do this, but it ensures that you don't lose content when the server crashes
    // See https://github.com/yjs/yjs#Document-Updates for documentation on how to encode 
    // document updates
  },
  writeState: (string, doc) => {
    // This is called when all connections to the document are closed.
    // In the future, this method might also be called in intervals or after a certain number of updates.
    return new Prosime(resolve => {
      // When the returned Promise resolves, the document will be destroyed.
      // So make sure that the document really has been written to the database.
      resolve()
    })
  }
})

wss.on('connection', setupWSConnection)

server.on('upgrade', (request, socket, head) => {
  // You may check auth of request here..
  /**
   * @param {any} ws
   */
  const handleAuth = ws => {
    wss.emit('connection', ws, request)
  }
  wss.handleUpgrade(request, socket, head, handleAuth)
})

server.listen(port)

console.log('running on port', port)

```

**Comment by CyriacBr** [comment]
@calibr @dmonad Awesome.
I'll take a close look at both your solutions, thanks a lot!

I'll comment again in case I have additional questions but so far it looks like everything I need has been provided.

**Comment by dmonad** [comment]
Great! I'll close this issue then.

**Comment by CyriacBr** [comment]
@dmonad Your solution works wonder.
I have just a little question about handling the `update` operation.  
You were suggesting to use the new API functions but they seem to help when you have two documents you want to manually sync. It seems that I can already get the final 'state' by accessing the `doc` sent in the update callback:
```
const serverDoc = new Y.Doc();
doc.on('update', (update, origin, yDoc) => {
      const state = Y.encodeStateAsUpdate(yDoc);
      Y.applyUpdate(serverDoc, state);
      //-- OR
      Y.applyUpdate(mergedDoc, update);

      const mergedText = serverDoc.getText('monaco').toString();
      const text = yDoc.getText('monaco').toString();
      console.log('mergedText :', mergedText);
      console.log('text :', text);
    });
```

Accessing the state directly from `yDoc` seems to return the final document already, so there's no need to use the new API?

For whoever who is interesting, the names of my rooms appear as `yDoc.name`. This allows me to save exactly why I need to specific tables because the front-end registers the rooms with specific IDs.

**Comment by dmonad** [comment]
The `update` event is fired with any keystroke - or any change on the shared document. The `update` variable is a granular update message. 

By doing `const state = Y.encodeStateAsUpdate(yDoc)`, you encode the complete document to an update message, which might be a bit expensive if you do that for every keystroke (or if you are working on large documents).

This is why I recommended to use @calibr 's approach of storing each update message as a unique key in the database. You could store each update as `{room-name}#{date.now()}` and iterate over all keys starting with `{room-name}` to create the document.

But I guess that this is only efficient with NoSql databases. Another approach to store the document would be to only store it when `writeState` is called. But you should also make sure to store the complete document in regular intervals - otherwise, you will loose data when the server process ends prematurely.

**Comment by CyriacBr** [comment]
Yes I noticed | `update` was firing at every keystroke. I was thinking of adding a debounce to reduce the workload.

> This is why I recommended to use @calibr 's approach of storing each update message as a unique key in the database. You could store each update as {room-name}#{date.now()} and iterate over all keys starting with {room-name} to create the document.

For my use case, I am only interested in the text content of the docs. I have a `File` table with a `content` field that needs to sync with Y documents.
But I think I can manage your proposition as well. Would this work to build a doc using the new API?
```
const completeDoc = new Y.Doc();
for ( const update of storedUpdates ) {
    Y.applyUpdate(completeDoc, update);
}
```

But I've been wondering how the initial doc on the client-side get populated. From `y-websocket` sources, it seems that I should retrieve the persistent data inside the `bindState` function and build the doc there.
```
// y-websocket/bin/utils.js
  const doc = map.setIfUndefined(docs, docName, () => {
    const doc = new WSSharedDoc(docName)
    doc.gc = gc
    if (persistence !== null) {
      persistence.bindState(docName, doc) // Build doc here
    }
    docs.set(docName, doc)
    return doc // since it is returned here
  })
```

If I do need to build the doc and return it inside `bindState` to populate the clients, I'd have no choice but to store each update because this seem to be the only way to build a doc.

**Comment by dmonad** [comment]
The debounce approach sounds good. This will probably work best with MySql. But you need to make sure that `writeState` only resolves after all remaining debounce callbacks have been called. Otherwise, there is no document to read from anymore.

> But I think I can manage your suggestion as well. Would this work to build a doc using the new API?

Yep

> But I've been wondering how the initial doc on the client-side get populated. From y-websocket sources, it seems that I should retrieve the persistent data inside the bindState function and build the doc there.

You can retrieve the complete document state (store this in the database after debounces: `const state = Y.encodeStateAsUpdate(yDoc)`) from the database and then apply it on the empty document when `bindState` is called (`Y.applyUpdate(doc, state)` where `state` is an Uint8Array received from the database).

Updates can encode the complete document or just granular updates. You may also apply them several times `Y.applyUpdate(doc, state); Y.applyUpdate(doc, state)` The second time won't actually do anything.

**Comment by CyriacBr** [comment]
Problem solved! Thanks for open sourcing Y-js.

**Comment by dmonad** [comment]
Sure, you are welcome! If you want to share what you built, please post it in https://discuss.yjs.dev :wink: 

That especially goes for you @calibr! I'd love to hear more about how people use Yjs.

**Comment by CyriacBr** [comment]
Sure. In fact, I've been contemplating another solution that does not rely on storing doc updates. Here's what I came up with:
* Listen to the update event and store the `update` values on a plain map<roomID, update[]>.
* Listen to on the client side when the user has cessed typing (debounce of 1ms)
* Send a request to the server to build the doc based on the stored updates on the map and retrive the content of ytext monaco.
* Persist it in my db.

Then, to populate the clients, inside `bindState` I fetch the persisted content, create a Y.Text, and send its state to the doc:
```
bindState: (docName, doc) => {
  const id = doc.name;
  const content = fetchSyncFromDB();
  const ytext = new Y.Text();
  ytext.insert(0, content);
  const state = Y.encodeStateAsUpdate(ytext.doc);
  Y.applyUpdate(doc, state);
}
```

I think this solution suits me more because I do not have to store the updates at each change and the workload is kept to a strict minimum. Persist data when the users stops typing.

I will sure make a post about on the forum and share how I incorporated Y-JS with NestJS, which is the backend framework I use.

**Comment by CyriacBr** [comment]
So, with minor changes, I was able to achieve what I wanted and it was working as expected until I tried to see what'd happen if the server crashed and reconnected while the user was editing.

What happens is that the persisted content retrieved inside `bindState` gets appended to the current client's document.  
That means during re-connection the user ends up with a whole duplicated content.
Looking at `y-monaco`'s [sources](https://github.com/yjs/y-monaco/blob/master/src/y-monaco.js#L129), loading the persisted state on the server counts as an insert update, which cause the doc content to be appended.

@calibr 's solution would cause the same problem if he's building the complete doc inside `bindState` too.

@dmonad I think this is a problem worth being looked at. I'm not urging you to think of a solution right away but I just wanted to let you know. I may be able to sort out something by forking `y-websocket` or `y-monaco` and tweaking it for my use case.

**Comment by CyriacBr** [comment]
I managed to solve the above problem by populating the client's Y.Text with initial data =)
```
this.ydocs[id] = new Y.Doc();
// this.ydocs[id].on('afterTransaction', (trans: any) => {
//   console.log('AFTER TRANS');
//   console.log('trans :', trans);
// });
socketProviders = new WebsocketProvider(
  `${window.location.protocol === 'http:' ? 'ws:' : 'wss:'}//${SERVER_URI}`,
  id,
  ydoc
);
const type = ydoc.getText('monaco');
type.insert(0, file.content); // <==== HERE
ysBindings = new MonacoBinding(
  type,
  editor.getModel(),
  new Set([editor]),
  socketProvider.awareness
);
```

**Comment by dmonad** [comment]
In Yjs it isn't really possible to set a starting-value. Since the client already had the document content, it synced it back to the server and you had the content twice. There are some ways around that, but if your solution works well for you I'm happy that you found a solution on your own :) 

There is not really a recommended way to handle Yjs on the server side. There are many options. But generally I recommend to populate the Yjs document only once and then store the encoded Yjs model and distribute this model to all clients. Then you never have to deal with duplicated content.

If you ever run into more troubles and want to adapt how you organize data, just come back and we can discuss further. Make sure to describe the exact use-case.

Happy hacking until then!

**Comment by CyriacBr** [comment]
> If you ever run into more troubles and want to adapt how you organize data, just come back and we can discuss further. Make sure to describe the exact use-case.

Thanks for the invitation. I'm going to test my app tonight with multiple users interacting simultaneously with the document. If there's any problem I'll let you know.

On a side note, would you accept a PR to provide type definitions for TS? I have a `yjs.dts` file I wrote quickly for my usage but I can extend it and send a PR.

**Comment by dmonad** [comment]
Yjs is actually fully typed. Although I use jsdoc annotations to define types (something that typescript supports). But they currently don't allow to generate tsc files if you have js files in the project. The README.md describes how you can enable Yjs type declarations. We could also automate generating `yjs.dts` by renaming all files to .ts and then run `tsc` to generate the dts file. But I haven't found time to do that in a simple script

**Comment by timcubb** [comment]
@dmonad Hi - i am also trying to get initial data for y-monaco using y-websocket, but I haven’t figured out how to get it to work. I want to have a workspace of several files which when the server starts, create a doc for each file and populate the data from a file. Then any client that connects can edit the document. I haven’t really seen anything as far as how to edit an existing doc document, only for starting a new document from scratch on the client. Any help would be appreciated :)

**Comment by dmonad** [comment]
Hi @timcubb , you created multiple threads on this topic. https://discuss.yjs.dev/t/creating-a-document-from-file-initial-document-state/85/4

**Comment by abdoolly** [comment]
@dmonad I admire yjs but, there might be a small problem that happened in y-websocket.

I think we need to re-open this issue since there is a solution you have made and with adding the `exports` field in the y-websocket and the new node.js versions only allowing subpath exports using the exports field now we are not able to access `y-websocket/bin/utils.js`

The code below now is not working  since we are now not allowed to require or import `y-websocket/bin/utils.js` if there is an alternative please tell us how or I can raise a PR to solve this issue and add the utils in the exports field.

what do you suggest ?

> ```js
> #!/usr/bin/env node
> 
> /**
>  * @type {any}
>  */
> const WebSocket = require('ws')
> const http = require('http')
> const wss = new WebSocket.Server({ noServer: true })
> const utils = require('y-websocket/bin/utils.js')
> const setupWSConnection = utils.setupWSConnection
> 
> const port = process.env.PORT || 1234
> 
> const server = http.createServer((request, response) => {
>   response.writeHead(200, { 'Content-Type': 'text/plain' })
>   response.end('okay')
> })
> 
> /*
>  Persistence must have the following signature:
> { bindState: function(string,WSSharedDoc):void, writeState:function(string,WSSharedDoc):Promise }
> */
> utils.setPersistence({
>   bindState: (documentName, doc) => {
>     // Here you listen to granular document updates and store them in the database
>     // You don't have to do this, but it ensures that you don't lose content when the server crashes
>     // See https://github.com/yjs/yjs#Document-Updates for documentation on how to encode 
>     // document updates
>   },
>   writeState: (string, doc) => {
>     // This is called when all connections to the document are closed.
>     // In the future, this method might also be called in intervals or after a certain number of updates.
>     return new Prosime(resolve => {
>       // When the returned Promise resolves, the document will be destroyed.
>       // So make sure that the document really has been written to the database.
>       resolve()
>     })
>   }
> })
> 
> wss.on('connection', setupWSConnection)
> 
> server.on('upgrade', (request, socket, head) => {
>   // You may check auth of request here..
>   /**
>    * @param {any} ws
>    */
>   const handleAuth = ws => {
>     wss.emit('connection', ws, request)
>   }
>   wss.handleUpgrade(request, socket, head, handleAuth)
> })
> 
> server.listen(port)
> 
> console.log('running on port', port)
> ```

**Comment by dmonad** [comment]
@CyriacBr Downgrading to an older nodejs version will likely fix the problem. The problem you mentioned will be fixed in the next major release of y-websocket.

**Comment by abdoolly** [comment]
@dmonad Thanks for your fast response 
Yes, I did actually downgraded the nodejs version but, this would be a temporary solution
when is the next major release going to happen?

**Comment by abdoolly** [comment]
@dmonad do you have any alternative solution for now other than downgrading the node version.

what we are trying to do is to persist the doc to a database that's why we needed to use the custom persistor if there is a better way I would be happy to re-implement it in my code ?

**Comment by dmonad** [comment]
You can copy the code or downgrade. I can't provide a fix for this in the current release because that would break running instances.
