### ISSUE TITLE
toJSON in xmlFragment is incomplete

### ISSUE THREAD

**Issue by disarticulate** [yjs/yjs#181]
Great work here. I'm working with prose-mirror, and trying to get the matching editor.view.toJSON function from the type? But it looks unfinished:
```
  toString () {
    return typeListMap(this, xml => xml.toString()).join('')
  }

  /**
   * @return {string}
   */
  toJSON () {
    return this.toString()
  }
```
Is this suppose to decode the xml fragments?

**Comment by dmonad** [comment]
Hi @disarticulate, this is the expected behavior. `toJSON` should return an XML-string when called on an Y.XmlFragment, Y.XmlElement, or Y.XmlText. 

It should be easy to create a function that traverses the Y.Xml types and returns the ProseMirror-JSON object that you are looking for. Yjs is editor agnostic and doesn't know anything about ProseMirror-specific content representations.

**Comment by disarticulate** [comment]
Ok.

**Comment by tommoor** [comment]
With the addition of `toJSON` available on `Y.Doc` is there any expectation that it should behave more how @disarticulate was expecting here? 

If I call `toJSON` on a doc from `y-prosemirror` I just get `{ prosemirror: undefined }` as the output. I'm not sure if this is a bug or I'm missing something… 🤔

**Comment by dmonad** [comment]
Hi Tom,

I'm going to deprecate the `toJSON` api on `Y.Doc`. This API is really confusing for newcomers.. 

You need to define the type before retrieving the content. 

For example, you could do `ydoc.get('prosemirror', Y.XmlFragment)` and then `ydoc.toJSON()` will work as expected.

You get a different result when you define 'prosemirror' differently: `ydoc.get('prosemirror', Y.Array)` and then `ydoc.toJSON()` will return `{prosemirror: [..]}`.
