### ISSUE TITLE
Significant slowdown when rendering multiple yjs connected components

### ISSUE THREAD

**Issue by LukenAgile42** [yjs/yjs#186]
```
import React, {useState} from 'react';
import * as Y from 'yjs'

import YjsQuill from "./YjsQuill";

function App() {
	const range = [...Array(100).keys()]
	const ydoc = new Y.Doc()

	return (
		<div>
			{
				range.map(
					i => (<>
							<YjsQuill key={i} room={i} ydoc={ydoc} text={'foo'}/><br/>
						</>
					)
				)
			}
		</div>
	);
}

export default App;
```

```
import React, {useEffect, useState} from 'react';
import {useQuill} from "react-quilljs";
import {WebsocketProvider} from 'y-websocket'
import {QuillBinding} from 'y-quill'


function YjsQuill(props) {
	const {quill, quillRef} = useQuill();

	const [provider, setProvider] = useState(null)

	useEffect(() => {
		if (quill) {
			setProvider(new WebsocketProvider('ws://localhost:1234', 'quill' + props.room, props.ydoc))
		}
	}, [quill]);


	useEffect(() => {
		if (provider !== null) {
			const yQuillTextYtype = props.ydoc.getText('quill')
			const binding = new QuillBinding(yQuillTextYtype, quill, provider.awareness)

			const handleObserve = e => {
				if (quill && e.delta[0]) {
					const text = e.delta[0].insert
					quill.clipboard.dangerouslyPasteHTML(props.text)
					yQuillTextYtype.unobserve(handleObserve)
				}
			}
			yQuillTextYtype.observe(handleObserve)
		}
	}, [provider])

	return (
		<div style={{width: 500, height: 300}}>
			<div ref={quillRef}/>
		</div>
	);
}

export default YjsQuill;
```
I was testing scalability and I found that on rendering 10 components, there is significant slowdown, at 100 it is unusable. I'm not sure if there is some optimization I'm missing, or whether having this many connections on 1 application is just something you should not do.

The reason for this being a concern for me, is in a highly collaborative app, having 10+ different collaborative widgets rendered at once is a quite realistic scenario. Is this doable with yjs?

**Comment by dmonad** [comment]
I'm almost certain that the issue is not with Yjs. Quill uses a lot more memory and CPU for initialization, so it is unrealistic that Yjs is the bottleneck.

With every release, I simulate hundreds of Yjs instances creating thousands of concurrent actions on a shared document. The complete test suite, including the other tests, runs in 2 seconds. 

https://github.com/dmonad/crdt-benchmarks is another resource for Yjs performance benchmarking of concurrent actions.

Please check the inspector and figure out where the problem is. Maybe you can run your tests without Yjs and compare. I don't know the impact of creating 100 websocket connections. Again. Use the performance inspector and compare. You are just limited by your browser, not by Yjs. 10 connections is definitely not a problem.

I hope you are not creating 100 connections to the same room from the same browser. I don't get why you would like to do that. **Create one connection for each room**. If you would create 100 Yjs instances listening to the same room-name, each change on the document would immediately trigger 100*2 (broadcastchannel + websocket) updates on the Quill document. There is no reason to do something like this. Quill updates the DOM. The DOM is slow.
