### ISSUE TITLE
Y.Array.push/insert([content]) is confusing

### ISSUE THREAD

**Issue by ckohnert** [yjs/yjs#191]
I realize it was likely intentional to make `Y.Array.push` and `Y.Array.insert` accept an array of elements to insert rather than the traditional single element, but it violates the expected behavior of these methods due to their intentional similarity to `Array` and is going to lead to frequent usage bugs and confusion among users.

Consider either renaming these methods and/or changing the behavior to accept varargs style content (i.e. `Y.Array.push = function(...content) { ... }` so that it more closely resembles the standard Array implementation (while still allowing efficient bulk insertions).

**Comment by dmonad** [comment]
Hi @ckohnert, 

you are not the first to bring this up. For v13, we definitely have to keep using the API we have. But you might be able to convince me to change the behavior of `.push([content])`. 

The reason why these methods accept only arrays is that I believe that `function(index, ...content)` is extremely bad and inefficient code if `content` could be indefinitely long. Here are some of my reasons:
• The maximum number of arguments for each browser is different. [Look here for a reference](https://stackoverflow.com/questions/22747068/is-there-a-max-number-of-arguments-javascript-functions-can-accept). `insert(...[1..33000])` will fail in old versions of chrome and nodejs, because it exceeds the maximum number of arguments. It will work in modern browsers though. I ran into many issues with `array.splice` because the function will work in some browsers and not in some others. Debugging and fixing this is a nightmare.
• Functions that are called with a variable number of arguments are deoptimized by the javascript engine. I put a lot of effort into finding code-deoptimizations, so I usually avoid vararg parameters completely.
• You can't write proper, typescript compatible, type annotations in JSDoc for `function(index, ...content)`.

I hope you understand some of my reasons why I implemented `Y.Array.insert(index, [content])` with two well defined parameters. I don't think I will change this behaviour. Now my question is if it makes sense to change `Y.Array.push`, because in the Yjs/lib0 ecosystem I usually completely avoid vararg functions.

I also implemented some benchmarks to prove my point that spread operators are slow: https://jsperf.com/vararg

**Comment by dmonad** [comment]
![Screenshot from 2020-04-15 20-44-36](https://user-images.githubusercontent.com/5553757/79376124-fe17a200-7f59-11ea-99f1-d572c5c4c56a.png)

Firefox really doesn't handle varargs well.

**Comment by ckohnert** [comment]
I can certainly understand the rationale, and I don't disagree. Mainly, I'd say the methods were unfortunately named and if you were going to change them, it'd probably be worth doing sooner rather than later. (And I'd argue it's probably still worth keeping a slower variant even if you did so.)

It's interesting that the spread operator is so much slower in the case you illustrate. Out of curiosity, I wonder what the overhead of creating the "container" array for the parameters is... i.e. the `[item]` is causing an allocation just to pass the single item, which your above benchmarks presumably aren't doing (though they may be in the spread case under the hood). If you allocate for each call, does it change significantly? I don't know enough about the internals of javascript implementations to know how good they are at dealing with things like that.

**Comment by dmonad** [comment]
> I can certainly understand the rationale, and I don't disagree. Mainly, I'd say the methods were unfortunately named and if you were going to change them, it'd probably be worth doing sooner rather than later. (And I'd argue it's probably still worth keeping a slower variant with the current names even if you did so.)

It is unlikely that I will change the names. I'm trying to keep the API stable. And again, for my own sanity, I avoid vararg functions. 

> Out of curiosity, I wonder what the overhead of creating the "container" array for the parameters is...

You can change the benchmark yourself. That's a pretty cool thing about jsperf - just click on the edit button. I don't really care about optimizing the case of inserting a single item. When you insert a bunch of items you probably already have them stored in an Array.

**Comment by dmonad** [comment]
Thanks for bringing up the issue. I hope that this will be helpful to others. I know that this unique behavior is frustrating to a lot of people. But I hope that they also understand my rationale behind this decision.
