### ISSUE TITLE
Recommended way to serialize an UndoManager

### ISSUE THREAD

**Issue by ISNIT0** [yjs/yjs#192]
I'd like to store individual changes (and then revert them later).

I thought I may be able to do this with the undo manager, but it doesn't seem possible. Is there a way to do this presently? Where should I look if I want to implement this functionality?

**Comment by dmonad** [comment]
Hi @ISNIT0 ,

You can use [the trackedOrigins feature](https://github.com/yjs/yjs#example-specify-tracked-origins) to capture specific changes. There are several examples in the README.

If you mean to persist the stacks of the UndoManager (i.e. save to a database), you simply need to serialize and restore the `undoStack` and the `redoStack` properties of the `UndoManager`. Make sure to disable the garbage collector in the Yjs document `const doc = new Y.Doc({ gc: false })` - otherwise you won't be able to restore changes.

I recommend to extend / build upon the existing UndoManager in Yjs.

**Comment by ISNIT0** [comment]
@dmonad 
You're my hero 🦸‍♂️

I had a play around with restoring the `undoStack` yesterday but to no avail, I guess it must have been missing the `gc` option.

Many thanks for all that you do 🙏
