### ISSUE TITLE
How does YJS's algorithm differ from the paper?

### ISSUE THREAD

**Issue by anchpop** [yjs/yjs#193]
From the readme: 

> Yjs implements a modified version of the algorithm described in this paper.

This got me wondering how YJS differs. For example, the readme says:

> We can't garbage collect deleted structs (tombstones) while ensuring a unique order of the structs.

But that wasn't my impression from the paper. Is that not the case in the current YJS implementation?

Also I see this section from the readme, which I didn't see in the paper. The changes seem pretty straightforward though. 

> If a user inserts elements in sequence, the struct will be merged into a single struct. E.g. `array.insert(0, ['a']), array.insert(0, ['b']);` is first represented as two structs `([{id: {client, clock: 0}, content: 'a'}, {id: {client, clock: 1}, content: 'b'})` and then merged into a single struct: `[{id: {client, clock: 0}, content: 'ab'}]`.

> When a struct that contains content (e.g. `ItemString`) is deleted, the struct will be replaced with an `ItemDeleted` that does not contain content anymore.

> When a type is deleted, all child elements are transformed to `GC` structs. A `GC` struct only denotes the existence of a struct and that it is deleted. `GC` structs can always be merged with other `GC` structs if the id's are adjacent.

The only thing I'm wondering about is how you remember the IDs of text that's been merged. Do you assume that if there are 10 tombstones next to each other, they have sequential IDs, that way you only need to store the first one's ID and how many there are?

I was wondering if this the extent of the changes to the algorithm, just out of curiosity! This is a really cool project and I appreciate the work a lot.

**Comment by dmonad** [comment]
Hey @anchpop ,

sorry there is a bit of confusion about this. 

In the first iteration of Yjs my approach was to remove items from the document, when we are pretty certain that they are not needed for conflict resolution anymore. Assuming we have three deleted items next to each other, we still need to keep then around in case somebody refers to them. But when the client is pretty certain that all clients deleted these structs, we could remove all structs from the document, except the first one. Because all new changes will only refer the first deleted struct. This is the notion of garbage collection in the paper.

But when I introduced offline editing in Yjs (using indexeddb), it wasn't possible to prevent issues with this approach anymore. One solution was to only do garbage collection on the server (if you have one), but even then this seemed like a hacky approach.

> The only thing I'm wondering about is how you remember the IDs of text that's been merged. Do you assume that if there are 10 tombstones next to each other, they have sequential IDs, that way you only need to store the first one's ID and how many there are?

This is exactly what is happening. And it works for all structs.
`Items` with string content are concatenated if possible.
Tombstones (`ItemDeleted` in Yjs) only preserve the amount of content and are also merged if the ids are next to each other.
`GC` structs are similar to tombstones, but don't preserve the order anymore. If a client executes 1000 changes on a type, and then the type is deleted. Then all that remains of the changes of that client is a single `GC{ id: [client, 0], length: 1000 }` struct. 

Merging is computationally inexpensive and heavily reduces the document size in real-world documents. But it was quite complicated to work with merged structs. With any change on the document, you need to make sure to split merged structs at the right position and make sure that they are merged back again after each transaction. Most of the complexity in Yjs comes from the merging/splitting logic. The conflict resolution part is actually just a few lines of code.

If you are interested you can compare Automerge (a CRDT without merging logic) with Yjs. You can really see that merging makes a huge difference even for randomized tests. https://github.com/dmonad/crdt-benchmarks
