### ISSUE TITLE
yjs + webpack : Cannot read property 'extend' of undefined

### ISSUE THREAD

**Issue by olivier-nerot** [yjs/yjs#214]
Hello,

With the following package setup : 
````
    "y-array": "^10.1.4",
    "y-indexeddb": "^9.0.3",
    "y-ipfs-connector": "^2.3.0",
    "y-memory": "^8.0.9",
    "y-prosemirror": "^0.3.4",
    "y-text": "^9.5.1",
    "y-websocket": "^1.2.5",
    "yjs": "^13.2.0"
````

I use the ES6 example from y-js.org page, in an electron app : 
````
import Y from 'yjs';
import yIndexeddb from 'y-indexeddb';
import yArray from 'y-array';
import yText from 'y-text';

Y.extend(yArray, yIndexeddb, yArray, yText);
````

which returns : 
````
TypeError: Cannot read property 'extend' of undefined
    at Module../node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/vue-cli-plugin-quasar/lib/loader.auto-import.js?kebab!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/layouts/P2P_Page.vue?vue&type=script&lang=js& (P2P_Page.vue:11)
    at __webpack_require__ (bootstrap:789)
    at fn (bootstrap:150)
    at Module../src/layouts/P2P_Page.vue?vue&type=script&lang=js& (P2P_Page.vue?c2c0:1)
    at __webpack_require__ (bootstrap:789)
    at fn (bootstrap:150)
    at Module../src/layouts/P2P_Page.vue (P2P_Page.vue?c344:1)
    at __webpack_require__ (bootstrap:789)
    at fn (bootstrap:150)
````
Y is undefined indeed.

If I use `import * as Y from 'yjs'`, the error is `yjs__WEBPACK_IMPORTED_MODULE_4__.extend is not a function`. I've also tried to import '/dist/...' files, building yjs from git, as said in an [issue](https://github.com/yjs/yjs/issues/84), but this solves nothing.

This may not come from yjs, as it looks like a common import error with webpack, but I wonder how to proceed, and an import example might be added in doc tohelp.

Btw, there often a link given to https://github.com/y-js/yjs/blob/master/README.v13.md but the link is broken.

Thanks

**Comment by dmonad** [comment]
Hi @olivier-nerot , who did refer you to y-js.org? 

It is an old unmaintained website from the university where I developed the framework initially. 

You'll find all the documentation in the GitHub repository https://github.com/yjs/yjs

There are even some demos that you can use as a starting point https://github.com/yjs/yjs-demos - all of them use webpack as a bundler.

**Comment by olivier-nerot** [comment]
Hi ! I used google to find y-js.org : first result to 'yjs' query :) 
I have tried tiptap demo with success indeed (impressive work btw). 

Now I am trying to make yjs work with libp2p / ipfs, to have peers discovery, and to share yjs message thanks to libp2p rooms (in order to have a room per shared doc, and a global room to announce new docs and users status).

I have only found an old project doing this : [y-ipfs-connector](https://github.com/ipfs-shipyard/y-ipfs-connector). I am trying to make it run again. But no luck for now : I am still unable to update the require/import part...

With yjs V13, it looks like there is no more Y.extend() method, and all the examples found on yjs-demos use Y.doc. Wondering if I have to give up, or if there is any hope to make yjs work in a libp2p network (with mdns / webrtc discovery + repo + rooms). Advices are welcome, and may be I should google more :)

**Comment by dmonad** [comment]
Right, thanks for reporting that. I found the old github repo that contains the website and deployed a hard-refresh to the github repo. So that is the last time we see the old yellow project site. (will take some time to trigger a deploy)

The new API is much easier to use. The v12 version (that y-ipfs-connector depends on) had a special connector class that you extended to exchange document updates. In v13 this has been replaced with a much easier to use update mechanism https://github.com/yjs/yjs#Document-Updates

I personally would start fresh. Both Yjs and IPFS have been heavily reworked. The IPFS devs started a new CRDT project for basic text editing. You could use their reference implementation to implement a new y-ipfs connector.

You could also try out [y-dat](https://github.com/yjs/y-dat) which is very similar in many ways (does encryption, discovery, ..).
