### ISSUE TITLE
export new Encoder/Decoder

### ISSUE THREAD

**Issue by calibr** [yjs/yjs#221]
As I can see the new implementation of encoder/decoder is now part of Yjs. Can we export new encoder/decoder classes from Yjs?

I need to do some low level operations on Items and then write them to binary, so I am using decoder/encoder from lib0, but I am getting errors from Yjs that `.writeInfo` is not implemented.

```
// I am trying to write an Item here
const encoderUpdate = encoding.createEncoder()
item.write(encoderUpdate, 0, 0) // causes .writeInfo is not implemented error
```

**Comment by dmonad** [comment]
There are two encoders now in Yjs. The v2 encoder produces smaller content but is incompatible with the v1 encoder. Both will be supported in the future and v2 is still experimental.

The V1 UpdateEncoder / UpdateDecoder just wraps the lib0/encoder. The v2 encoder does RLE encoding (and other encoding technologies) on the data. You can find a basic implementation here: https://github.com/yjs/yjs/blob/main/src/utils/UpdateEncoder.js

At the moment I don't want to export this because that would mean that I would need to keep its API stable. But I'm sure we can find another approach that works for you.

What exactly do you write to the encoder?

You could overwrite `item.write` and write your custom data to the `encoder.restEncoder`.

**Comment by calibr** [comment]
@dmonad I use a temp encoder to write items when I am returning a doc to a specific state back in history, code looks like this:

```js
export function backDocToState(doc, state) {
  console.log('back doc to state', state, typeof state)
  const { ss, ds } = state
  const needState = new Map<number, number>(ss)
  // we copy structs to encoder until specific state
  // and pack them in sync message 2
  // then create a new doc and feed it with the sync message 2
  const encoder = encoding.createEncoder()
  encoding.writeVarUint(encoder, syncProtocol.messageYjsSyncStep2)
  let len = 0
  const tempStructs = []
  const encoderUpdate = encoding.createEncoder()
  console.log('write number of states', needState.size, needState)
   // write # states
  encoding.writeVarUint(encoderUpdate, needState.size)
  for (let user of needState.keys()) {
    let clock = needState.get(user) || 0
    // because in yjs state stores next structu id we need to substract 1, to not get next structure, that
    // was created after the needState had been captured
    const userItems = doc.store.clients.get(user)
    console.log('running findIndexSS', user, clock)
    const endIndex = findIndexSS(userItems, clock - 1)
    // write # encoded structs
    encoding.writeVarUint(encoderUpdate, endIndex + 1)
    // write first id
    let isFirstIdWritten = false
    for(let i = 0; i <= endIndex; i++) {
      let item = userItems[i]
      if(item.id.clock + item.length > clock) {
        splitItem({ _mergeStructs: new Set() }, item, item.id.clock + item.length - clock)
      }
      if (!isFirstIdWritten) {
        isFirstIdWritten = true
        writeID(encoderUpdate, Y.createID(user, item.id.clock))
      }
      item.write(encoderUpdate, 0, 0)
    }
  }

  const deleteSet = {
    clients: new Map()
  }
  for(const [userId, clock, len] of ds) {
    if(!deleteSet.clients.has(userId)) {
      deleteSet.clients.set(userId, [])
    }
    deleteSet.clients.get(userId).push({
      clock,
      len
    })
  }

  writeDeleteSet(encoderUpdate, deleteSet)

  encoding.writeVarUint8Array(encoder, encoding.toUint8Array(encoderUpdate))

  const buf = encoding.toUint8Array(encoder)
  const decoder = decoding.createDecoder(buf)
  // replace current doc
  const newDoc = new Y.Doc()
  newDoc.transact(() => {
    console.log('reading sync message for the new doc')
    syncProtocol.readSyncMessage(decoder, encoding.createEncoder(), newDoc)
  })

  return newDoc
}
```

it is not optimal, but worked for me :)

**Comment by dmonad** [comment]
Yeah this sounds like a good usecase.

How about you rework this function and submit a PR to make it part of Yjs?

I don't want to expose to much Yjs internals. But I can maintain this function as part of Yjs as it seems generally useful.

Instead of splitItem use `findIndexCleanStart` and even though you are probably throwing away the original doc, you should use transactions if this function is part of Yjs.

**Comment by calibr** [comment]
@dmonad ok, so we can close this for now I think. I will try to rework this and submit a PR, so we can close https://github.com/yjs/yjs/issues/159. Thanks for the info
