### ISSUE TITLE
Sync nested Y.Type between two docs

### ISSUE THREAD

**Issue by raedle** [yjs/yjs#242]
Is it possible with `yjs` to sync nested states (`Y.Type`) between two `Y.Doc`? The example below has `doc1` with a `Y.Array` `arr`. The `arr` can have multiple `Y.Text` items. Any update to `doc1` will be applied to `doc2`. The expectation is that `doc1` and `doc2` will eventually have the same state. However, while `arr` in `doc1` has 1 `Y.Text` item, `arr` in `doc2` is undefined.

What am I missing?

Thanks!

**Example**
```
const Y = require('yjs');

const doc1 = new Y.Doc();
const doc2 = new Y.Doc();

// Sync changes between doc1 and doc2
doc1.on('update', update => Y.applyUpdate(doc2, update));

const arr = doc1.getArray('arr');
const txt = new Y.Text('text1');
txt.insert(0, "text2");
arr.push([txt]);

console.log({
    arr: arr.toJSON(),
    txt: txt.toJSON(),
})

console.log('doc1', {
    doc1: doc1.toJSON(),
});

console.log('doc2', {
    doc2: doc2.toJSON(),
});
```

**Output**
```
{ arr: [ 'text2text1' ], txt: 'text2text1' }
doc1 { doc1: { arr: [ 'text2text1' ] } }
doc2 { doc2: { arr: undefined } }
```

**Expected output**
```
{ arr: [ 'text2text1' ], txt: 'text2text1' }
doc1 { doc1: { arr: [ 'text2text1' ] } }
doc2 { doc2: { arr: [ 'text2text1' ] } }
```

**Environment Information**
- Running `yjs@13.3.2` in Node `v10.16.3`

**Comment by raedle** [comment]
**re my report above:**

The documents `doc1` and `doc2` **are** being synced, but `doc2.toJSON()` has a different output than `doc1.toJSON()`.

The following code shows the difference between `doc2.toJSON()` and accessing the `Y.Text` type directly.

```
console.log('doc2', {
    doc2: doc2.toJSON(),
    txt2: doc2.getArray('arr').toArray()[0].toString(),
});
```

**Output**
```
doc2 { doc2: { arr: undefined }, txt2: 'text2text1' }
```

**Comment by dmonad** [comment]
Hi @raedle ,

This is (unfortunately) the expected behavior. You need to define the type of `'arr'` first before printing it with toJSON. I.e. do `doc2.getArray('arr')` once before calling toJSON. Since doc2 doesn't know that `'arr'` is an YArray, it simply prints undefined.

In hindsight implementing toJSON on YDoc was a bad idea. There is no way to fix this problem. The top-level types are dynamic by design. One could request a top-level type as an YArray, while another process requests the top-level type as an YXmlFragment.
