### ISSUE TITLE
Best Practice for Drawing Style Applications?

### ISSUE THREAD

**Issue by Francois-Laberge-Bose** [yjs/yjs#256]
I'm prototyping a Figma-like zoomable Storyboard app. One thing I want to do is create rectangle vector graphic elements. As is typical I want to create rectangles by doing:

 1. Choose the rectangle tool
 1. When a mousedown or touchdown occurs, start dragging logic
 1. As you are dragging you are controlling the dimensions of the rectangle
 1. When you get a mouseup/touchup, you create the rectangle permanently
 1. If you use a `Y.UndoManager` instance and call undo, it should remove the rectangle

This UX pattern will come up for many dragging experiences like dragging to change the position of an element or resizing it. It's nice if others can see your in-progress creation, moving, resizing, and etc. An easy way to have it so people can see these actions live is to just create and modify the sharetypes as you are changing them. The issue is that this probably creates a lot of data but most importantly it makes the expected undo/redo not work.

I was wondering if anyone has a recommendation for how to do these types of UX. I was thinking of using the awareness type channels, but it probably gets messy quickly.

Hope I'm making sense here.

Thanks in advance, 
Francois

**Comment by izuchukwu** [comment]
Working on something similar. I commit the changes straight to the `Y.Doc`, but for dragging actions that cause rapid changes (e.g. resizing an element, dragging the color handle in the color picker) I throttle the commits using the `throttle-debounce` library.

Awareness is one path, but I'd agree that that would get messy quickly. I've not tried to use `Y.UndoManager`, I figured making something this complex, I'll have to roll an undo solution on my own later on.

**Comment by Francois-Laberge-Bose** [comment]
@izuchukwu thanks for the quick reply. I don't follow what you are doing exactly with throttling the commits, could you be more specific? Much appreciated!

**Comment by izuchukwu** [comment]
@Francois-Laberge-Bose I throttle the changes to the Y.Doc document. For example, while you are creating a rectangle with a rectangle tool, the browser will continuously fire `mousemove` events, which you use to change the rectangle's size in the Y.Doc. However, I throttle the rate of changes to the Y.Doc (solving the issue of "this probably creates a lot of data").

As I don't use `Y.UndoManager`, this was my most important problem and so far, solves the issue for me.

**Comment by Francois-Laberge-Bose** [comment]
Ah, because you don't use UndoManager then it works well enough, ok makes sense. Thanks.

**Comment by dmonad** [comment]
The UndoManager captures changes within a timeout. So even when you drag for a few seconds, only a single undo operation will be saved.  You could increase the timeout if necessary, but it generally does the right thing. If necessary you could fork UndoManager and adapt it to your needs.

There are some caveats when storing a lot of data in Yjs types. Setting data on a Y.Map is basically free when you do it several times on the same field: `ymap.set('pos', { x: 1, y: 1}); ymap.set('pos', { x: 1, y: 2}), ymap.set('pos', { x: 1, y: 3}), ..`. Meanwhile `ymap.set('x', 1); ymap.set('y', 2); ymap.set('x', 2); ymap.set('y', 3),..` will create a lot of metadata because you write to different keys. 

The best approach would be to try out what works best and avoid expensive operations. 

Every time you write to a Yjs type you will create an update message that is sent to all other peers. This works pretty well in the drawing demo at https://yjs.dev. But a better approach would be to throttle writes to the Yjs document while dragging, as @izuchukwu  mentioned.

In any case, using UndoManager is probably a good choice. You should read the API a bit to make sure that you capture the events efficiently.

**Comment by Francois-Laberge-Bose** [comment]
@dmonad Hmmmm, I had thought the "increase UndoManager timeout" wouldn't work, but I guess it does work if you just take responsibility for calling `Y.UndoManager.stopCapturing`. 

Yeah, I guess I should read the code in general, more to see ensure optimal trade-off in responsiveness/awareness to data creation.

Also, thanks for creating this lib! I like how many integrations you've made with text editors. I'm going to play around with a storyboard with multiple instances of Quill editors and work through the issues.

I'll close this Issue, I have some good leads. Thanks @izuchukwu again too!

**Comment by Francois-Laberge-Bose** [comment]
I should add for future explorers, that for drawing apps it's best to be optimizing vector lines with curve smoothing and such as well, which will reduce traffic/storage-size. For dragging objects, throttling definitely to frame rate, or a bit lower is just the least wasteful.

**Comment by dmonad** [comment]
Great, thanks for sharing! It would be great if you could summarize your findings in discuss.yjs.dev when you are done.

For me this is a really interesting application as well, but I haven't worked on a serious drawing app yet myself. The best drawing app based on Yjs is currently room.sh - but even that could be improved heavily.

**Comment by izuchukwu** [comment]
@Francois-Laberge-Bose Good point on the particular rate to throttle to! I wanted to throttle even slower to save bandwidth as 60 messages per second sent out to all other peers can grow quite quickly with higher peer counts. I'll soon be switching to throttling within the `WebSocketProvider` itself, throttling outgoing peer updates while allowing local document changes to affect all listeners (the on-screen element, value fields in a details sidebar, etc.) immediately.

@dmonad Great work on the library. I'll have to take a second look at `Y.UndoManager`. Currently putting it through its paces for a serious canvas-style app!
