### ISSUE TITLE
Replace encoding and decoding to protobuf.

### ISSUE THREAD

**Issue by firstfhy** [yjs/yjs#262]
Hi, I am working on the Jupyter Realtime Collaboration project (https://github.com/jupyterlab/rtc) and one of the requirement is to avoid Node.js as dependency for the user.
I hope the websoket encoding and decoding to protobuf. Because protobuf is a common protocal and easy to expand new interface.

非常有幸使用这个项目，我希望能够使用 protobuf 替代现在的websoket网络消息序列化和反序列化，因为 protobuf 是一个通用的协议而且容易扩展新的借口。

**Comment by dmonad** [comment]
Hi @firstfhy,

Yjs uses tabular encoding, different RLE encoders, and many other techniques to create a compact update format. protobuf is a nice library to create protocols. But it is simply unsuited to model the Yjs document format.

Furthermore, it is unlikely that I will replace the encoding technology because the update-format is standardized. I don't see a reason to use something different.

You can use Protobuf, or any other library to send Yjs updates to other peers. Yjs produces small binary blobs that you can send to other peers. You don't need to understand the content of Yjs messages. 

Please also have a look at ticket #261 . I plan to create a native port of Yjs to Rust. We will use language bindings to make it possible to use the Y update format in Python.

I'm going to close this ticket. Feel free to comment further or discuss in the related issues.

**Comment by firstfhy** [comment]
Thanks!
