### ISSUE TITLE
Allow transactions to be async

### ISSUE THREAD

**Issue by andrew-knack** [yjs/yjs#265]
**Checklist**

[ ] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
[ ] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Is your feature request related to a problem? Please describe.**
For multiple changes to considered to be merged as a single change over an arbitrary amount of time. Currently transaction doesn't allow that.

**Describe the solution you'd like**
Allow the [transaction function](https://github.com/yjs/yjs/blob/main/src/utils/Transaction.js#L378-L405) to take in a async function.

**Describe alternatives you've considered**

Not an alternative but I did test that changing the transaction function to async and awaiting the `f` call seemed to work.

**Additional context**
The amount of time that it will take for the transaction is arbitrary based on the user actions so changing the captureTimeout on the `UndoManager` isn't an option.

**Comment by dmonad** [comment]
What is the use-case for this?

**Comment by andrew-knack** [comment]
I need more control over what is considered a single entry in the undo manager. 
In my use case I essentially want to start a transaction on mouse down and end the transaction on mouse up.

**Comment by dmonad** [comment]
Yeah, that makes sense.. But I think that we rather implement this feature in the UndoManager and don't mess with transactions.

Transactions are meant to be atomic changes. If they would be asynchronous, we would need to deal with a lot of new issues (e.g. what happens when two async transactions happen concurrently?).

I'm thinking that we should rather implement something like `undoManager.startCapturing()`. When this method is called, we would capture until `undoManager.stopCapturing()` is called. What do you think? Also, would you be interested in submitting a PR for that?

**Comment by andrew-knack** [comment]
> Transactions are meant to be atomic changes. If they would be asynchronous, we would need to deal with a lot of new issues (e.g. what happens when two async transactions happen concurrently?).

Wouldn't it be the same as transactions are now, the outer captures the inner transaction regardless if it's async or not?

> What do you think? Also, would you be interested in submitting a PR for that?

I've currently got some deadlines I need to meet but during the december break I can give it a go, let's just settle on a design first. 

> I'm thinking that we should rather implement something like undoManager.startCapturing(). When this method is called, we would capture until undoManager.stopCapturing() is called.

There is a part of my use case that I implied but didn't outright say, the transaction also gives control to the user when a change is emitted.

**Comment by dmonad** [comment]
I'm not generally against the idea to make transactions async. You are right that it does give the user more control.  It is just more complexity that I would have to deal with. 

Currently, you can indeed create nested transactions within the `type.observer` handlers. This feature was carefully implemented but it took me quite some time to get right.

When we introduce async transactions, then transactions will not just be created within event handlers (which are technically after the transaction is finished), but also within another transaction itself. A remote transaction might mingle with a transaction created locally. We also can't just dispatch two separate transactions because I made the assumption that transactions are atomic when computing changes. So we really need to finish one transaction before creating the next one.

The providers heavily rely on transactions being either local or remote. A lot of other projects (the editor bindings for example) rely on a unique transaction origin. While these problems can surely be solved, I don't necessarily want to open this Pandora's Box.

**Comment by andrew-knack** [comment]
I thought I replied to this ticket, sorry about the delay. I'm not overly sure on how a local and remote transactions can interact so forgive my naivete. 

When I think async transaction I'm think of essentially collecting changes, like it does so right now, but over an arbitrary amount of time and committing the change as a single atomic change after the function completes. The current transaction model should **_hopefully_** still hold. Essentially this is the change:

```js
export const transactAsync = async (doc, f, origin = null, local = true) => {
  const transactionCleanups = doc._transactionCleanups
  let initialCall = false
  if (doc._transaction === null) {
    initialCall = true
    doc._transaction = new Transaction(doc, origin, local)
    transactionCleanups.push(doc._transaction)
    if (transactionCleanups.length === 1) {
      doc.emit('beforeAllTransactions', [doc])
    }
    doc.emit('beforeTransaction', [doc._transaction, doc])
  }
  try {
    await f(doc._transaction)
  } finally {
    if (initialCall && transactionCleanups[0] === doc._transaction) {
      cleanupTransactions(transactionCleanups, 0)
    }
  }
}
```

I do understand you don't want to open this can of worms because you're essentially on the hook to support it going forward. If it's not a an idea you're comfortable with feel free to close this ticket.

**Comment by dmonad** [comment]
Thanks @andrew-knack ,

> collecting changes, like it does so right now, but over an arbitrary amount of time and committing the change as a single atomic change after the function completes

I hinted in the previous reply that this might be problematic. E.g. when an editor-binding creates a transaction while the async transaction is running. In that case, the solution you proposed will simply reuse the currently running transaction. This will still work, but the problem is that the reused transaction now has a different transaction-origin. I indeed don't want to open this "can of works", as you nicely put it :)

We can enable your use-case in the UndoManager.
