### ISSUE TITLE
y-trix

### ISSUE THREAD

**Issue by kwent** [yjs/yjs#269]
Hi, and thank you for your hard work !

[Trix Editor](https://trix-editor.org/) is shipped by default using [ActionText](https://edgeguides.rubyonrails.org/action_text_overview.html) in **Rails** stacks. i had like to implements **yjs** without having to install another editor. ( + they already integrated upload images for [ActiveStorage](https://edgeguides.rubyonrails.org/active_storage_overview.html) etc. so lot of magic already happens using Trix)

How hard would it be to create a `y-trix` binding ? There are using a [document model](https://github.com/basecamp/trix#understanding-the-document-model) so i'm sure it would be possible but unsure they are exposing the API for it.

One other thing is that i don't think they have multi cursors support as far as i know.

Am i missing anything ?

Regards

**Comment by dmonad** [comment]
Hi @kwent ,

Trix seems to have an immutable document model - very similar to Slate and ProseMirror. The idea of the editor bindings is to 1. reflect all changes from the Yjs document to the editor, and 2. all changes from the editor to Yjs.

It is often hard to translate between the different document models. ProseMirror has a rather complicated document model (supporting attributed text, that is not native to JSON). Others have a simple document model that simply represents everything as a JSON-object.

I recommend that you experiment a bit with what you are trying to achieve. Start with the most basic implementation and continue to improve the editor binding. Feel free to come back and ask questions.

The y-prosemirror binding is probably the most complicated editor binding. I simply mapped the ProseMirror state (which is basically JSON) to [Yjs types](https://docs.yjs.dev/getting-started/working-with-shared-types). I started by recomputing the complete editor-state every time something changed.

1. When the Yjs document changes, you could simply call `type.toJSON()` to transform it to JSON. Later, you can improve memory-usage by caching states: When a type did not change, use the cached state from the previous version (use a Map/WeakMap that maps from Yjs type to a JSON state).
2. When the editor changes, you need to find some way to calculate the differences and apply them to the Yjs document. Since Trix seems to be immutable, you probably want to find the changed nodes (strict comparison), and apply the diff to the Yjs document. Maybe Trix has a more convenient representation that you could use instead.

Another approach would be to transform all Trix changes to the [rich-text delta format](https://quilljs.com/docs/delta/). The rich-text format is fully supported by [Y.Text](https://docs.yjs.dev/api/shared-types/y.text).

In any case, I recommend using [Yjs' undo-manager](https://docs.yjs.dev/api/undo-manager) instead of the Trix's undo manager. It works in collaborative scenarios and will use less memory because Trix stores every state that is saved in Trix's undo manager.

**Comment by dmonad** [comment]
@kwent Let's continue the discussion on the discussion board. https://discuss.yjs.dev/

I like to use Github's issues for bugs and feature requests to this library only.
