### ISSUE TITLE
What method should I use to get the user who is editing

### ISSUE THREAD

**Issue by jacintoface** [yjs/yjs#279]
What method should I use to get the user who is editing

**Comment by Tpuljak** [comment]
The way yjs bindings display which user is editing which line of a document is by tracking the users' cursors.

Handling cursors is separate from handling content changes but since you track the cursor of every user you can see which user is changing which part of the document.

If you haven't already, check out the Monaco editor binding ([link](https://github.com/yjs/y-monaco)) and the [demo](https://github.com/yjs/y-monaco) (open the demo in your one browser and one more in incognito mode or another browser).

The way I track users in my project is similar to the Monaco binding in that repo. You just have to handle selection changes from your users and render them as decorations in the editor.

I'm not sure if I answered you question but if not, please elaborate a little bit more and so I could assist you further.

**Comment by ilovedesert001** [comment]
check this
https://docs.yjs.dev/api/about-awareness
