### ISSUE TITLE
Full JSON representation

### ISSUE THREAD

**Issue by streamich** [yjs/yjs#284]
Is there a way to represent the whole document (not just data but including all "items" in the linked lists) in some human-readable JSON format. Basically, I am looking for something like the public `Y.encodeStateAsUpdate` API but which would return JSON instead of UintArray.

**Comment by dmonad** [comment]
Hi @streamich ,

You can use `Y.logUpdate(update)` to log the content of an update message.

**Comment by streamich** [comment]
Thanks!

**Comment by streamich** [comment]
BTW, what do you think about standardizing a JSON format for representing JSON CRDT, something like below. Where each type of JSON value is represented by type-specific `JSONCrdtNode*`.

![image](https://user-images.githubusercontent.com/9773803/110974717-1d33d500-835f-11eb-8f9e-74aae14c2546.png)

**Comment by streamich** [comment]
Basically on object like

```json
{
  "foo": "bar"
}
```

In JSON-CRDT format would be encoded as:

```json
{
  "node": {
    "t": "o",
    "l": "user1:0",
    "r": "user1:0",
    "chunks": {
      "user1:0": {
        "l0": "",
        "l1": "",
        "r0": "",
        "r1": "",
        "key": "foo",
        "var": {
          "t": "s",
          "l": "user1:1",
          "r": "user1:1",
          "chunks": {
            "l0": "",
            "l1": "",
            "r0": "",
            "r1": "",
            "var": "bar",
          }
        }
      }
    }
  }
}
```

**Comment by dmonad** [comment]
What is the use-case for a JSON encoder? Would you actually use it in your system?

**Comment by streamich** [comment]
It would be used as a working plain JSON data structure with multiple purposes:

- It would be a standardized way of encoding linked lists, and hence many CRDT implementations in JSON.
- That representation would be used to download the initial full document over HTTP (or whichever transport), it could even be considered a REST resource.
- When performing CRDT operations that structure would actually be used as the source of truth for the CRDT JSON object in memory and all operations would mutate (or like in Redux create a new copy) that JSON representation, unlike it is now in `yjs` (not to say anything bad, `yjs` is great) where all types/items/contents are native JS classes.
- CRDT algorithm could be described using this data structure, which would make implementations easier to port to other languages.
- Test cases could also be written using this JSON CRDT encoding&mdash;which would make test cases portable across languages or implementations.

**Comment by streamich** [comment]
BTW, I'm just learning CRDTs, so if you know good reasons why it is a bad idea, I am very interested.

**Comment by dmonad** [comment]
You might wanna look into [Ron](http://replicated.cc/) which aims to standardize encoding in different encodings. I like the approach, but I can't use it in Yjs because it implements a unique, heavily optimized encoder.

CRDTs that use JSON encoding generally don't perform well in JavaScript. Parsing JSON is expensive and allocates memory inefficiently. I indirectly make use of the fact that modern JavaScript engines optimize memory allocation of the same object (in Yjs the "Item" class). I talk about this more in https://blog.kevinjahns.de/are-crdts-suitable-for-shared-editing/

Another advantage of the Yjs encoder is that it achieves high compression at no cost without using an expensive generic compression algorithm (e.g. zip). In some cases, the encoder achieves 300x better compression rates & 1000x better performance than other CRDTs that use JSON encoding: https://github.com/dmonad/crdt-benchmarks

> When performing CRDT operations that structure would actually be used as the source of truth in memory and all operations would mutate (or like in Redux create a new copy) of that JSON representation, unlike it is now in yjs (not to say anything bad, yjs is great) where all types/items/contents are native JS classes.

I'm a big fan of immutable state. But I believe that this is not the correct solution for implementing a CRDT. However, you should be able to implement immutable state on-top of Yjs. This has been done in https://github.com/tandem-pt/zustand-yjs

> CRDT algorithm could be described using this data structure, which would make implementations easier to port to other languages.

I'm working to port Yjs to other languages. There will be a base implementation in Rust and many ports to other languages based on the Rust port and language bindings. https://github.com/yjs/y-crdt

The advantage of JSON encoding is that it is human-readable. But CRDTs that use JSON encoding don't perform well in practice. With compression techniques like RLE encoding, variable-length encoding, and tabular encoding we can make CRDTs viable in practice. For this reason, I don't recommend JSON encoding as a go-to solution.

**Comment by streamich** [comment]
Thanks for the detailed explanations and valuable links!

Meanwhile, for the JSON representation, I was thinking maybe a flat type/content  structure would work better? Instead the structure could be:

```ts
/** Types of complex nodes. */
export const enum JsonCrdtNodeTypes {
  String = 0,
  Array = 1,
  Object = 2,
}

export type JsonCrdtNullNode = null;
export type JsonCrdtBooleanNode = boolean;
export type JsonCrdtNumberNode = number;
export type JsonCrdtStringNode = [type: JsonCrdtNodeTypes.String, firstChunkRef: string];
export type JsonCrdtArrayNode = [type: JsonCrdtNodeTypes.Array, firstChunkRef: string];
export type JsonCrdtObjectNode = [type: JsonCrdtNodeTypes.Object, firstChunkRef: string];

export type JsonCrdtStringNodeChunk = [next: string, value: string];
export type JsonCrdtArrayNodeChunk = [next: string, valueRef: string];
export type JsonCrdtObjectNodeChunk = [next: string, key: string, valueRef: string];

export type JsonCrdtNode = 
  | JsonCrdtNullNode
  | JsonCrdtBooleanNode
  | JsonCrdtNumberNode
  | JsonCrdtStringNode
  | JsonCrdtArrayNode
  | JsonCrdtObjectNode;

export type JsonCrdtChunk =
  | JsonCrdtStringNodeChunk
  | JsonCrdtArrayNodeChunk
  | JsonCrdtObjectNodeChunk;

export type JsonCrdtRef = JsonCrdtNode | JsonCrdtChunk;

export interface JsonCrdtBlock {
  startRef: string;
  refs: Record<string, JsonCrdtRef>;
}
```

Where a simple object like

```json
{
  "foo": "bar"
}
```

Could be represented as

```json
{
  "startRef": "a",
  "refs": {
    "a": [2, "b"],
    "b": ["", "foo", "c"],
    "c": [0, "d"],
    "d": ["", "bar"]
  }
}
```

This way all types and items are in one flat `refs` list. And similar to how `yjs` does it, the ref IDs could be lamport time stamps and deltas could a subset of the most recent refs.

**Comment by dmonad** [comment]
A flat JSON structure still allocates too many objects on the heap. A Text CRDT could easily consist of 100k `Item` instances (`Item` is a node in the Yjs CRDT that represents a chunk of text). The cost of allocating objects is the single performance bottleneck when implementing a CRDT in dynamic languages like JavaScript. Heap allocations are generally expensive and consume additional memory. Additionally, each object on the heap needs to be tracked by the garbage collector. In my blog post, I talk about how I optimized Yjs to perform well in a dynamic language.

Your example of a flat JSON representation would allocate 24 objects on the heap: 17 strings, five arrays with dynamic length, and two key-value stores (`{}`) with dynamic size. Allocating objects of dynamic size are especially costly because the JavaScript engine doesn't know beforehand how much memory to allocate. Overall, your structure for a simple key-value entry would allocate 644 bytes of memory (check the retained size). 

![Screenshot from 2021-03-13 22-27-19](https://user-images.githubusercontent.com/5553757/111044863-65c8bc80-844b-11eb-902c-b78c7af7bf87.png)

Meanwhile, Yjs would represent the above key-value entry using 94 bytes (94=88+6) of memory in a single `Item` allocation and two string allocations for the key-value entries. (this is also shown in the blog post)

Regarding encoding size: Yjs would encode the above document in ~16 bytes. Your flat JSON map encodes to a string with a length of 96 characters.

I don't want to give the impression that JSON is bad. JSON is awesome for any kind of unstructured document. It is human-readable and generally performs well. But CRDTs are highly structured, potentially large documents with repetitive information. Previous attempts at using JSON for representing updates (e.g. Yjs <=v12 or Automerge) show that JSON is not suited for larger documents. 644 bytes of memory for a single key-value entry (which can certainly be optimized) is simply too inefficient for real-world applications. I think there is some benefit in expressing the update format as JSON, so that interested users can learn how updates are structured and applied. But I don't want to give the impression that it is a viable option for production usage.

**Comment by streamich** [comment]
I see your point (that CRDTs inevitably generate metadata overhead, they are a "data type" after all), that you need a very efficient user client implementation to save heap memory and you ideally want to have a compact binary encoding for the network. I absolutely agree with that!

But what I'm thinking, is that there still is room for a specification for JSON CRDT. That specification could lay down some basic data types for JSON CRDT type and operation encoding in JSON. The JSON encoding, of course, can be converted to a binary one.

Basically I'm thinking about something like JSON Patch, but something specifically for CRDTs, call it __JSON CRDT Patch__. The key difference with JSON Patch could be that the `path` property in JSON Patch operations is JSON Pointer to a location in JSON value, whereas in JSON CRDT Patch the `path` property would an ID of some previous operation, basically, in `yjs` terms it would be an `ID` of an `Item`. And each JSON CRDT Patch operation is basically a Yjs `Item`. And patch is a transaction.

JSON CRDT Patch | Yjs
-|-
Logical timestamp/ID | `ID`
Operation | `Item` or `AbstractType`
Patch | Transaction

Here is a little example: https://onp4.com/@vadim/p/vipcysgunk

**Comment by streamich** [comment]
![image](https://user-images.githubusercontent.com/9773803/111170748-92441c00-85a4-11eb-8f42-1ec76641b1a1.png)

**Comment by dmonad** [comment]
Would these operations actually commute, or do you need them only to send them to some kind of server. Are you trying to avoid loading the actual Yjs document to memory? I don't understand your motivation yet.

> The JSON encoding, of course, can be converted to a binary one.

If JSON encoding can be converted to a binary one (and probably vice versa), what is the advantage of using the JSON encoding. As I mentioned before, a JSON encoding is simply not sufficient for real-world applications. I don't see why I would go through the trouble to develop a JSON encoding without an actual use-case in mind.

**Comment by streamich** [comment]
My motivation is to create some sort of a standard like [JSON Patch](https://tools.ietf.org/html/rfc6902), but something for CRDTs, I guess something like RON but dedicated to JSON data type.

**Comment by dmonad** [comment]
Hey @streamich ,

sorry for the late reply. I'm not sure if it is feasible to create a JSON representation just for the sake of using JSON instead of binary encoding. I still don't understand the advantages. 

For manipulating content you should rather use the methods that are provided by Yjs. You could also add functionality for Yjs to accept changes that are expressed in the JSON Patch format. Yjs already supports the Quill Delta format, which was originally developed for Operational Transformation. 

I feel you might be interested in something like the json1 type in https://github.com/ottypes

**Comment by fedekau** [comment]
One of the advantages of using a JSON structure it because it is a bit more human readable. In our case we save snapshots of the document in json format that can be queried afterwards. We save it by doing `doc.toJSON()` and we also have a recursive function that allows us to recreate a document from a JSON structure that we previously saved.

That also decouples us from YJS, so in the future if we need to migrate away from YJS we already have the data in a JSON structure.

I know this is a different case than what is proposed here, but I wanted to contribute some ideas that we are using.

**Comment by gaurav21r** [comment]
@fedekau @streamich  The biggest use case for JSON is not just in _Human Readability_ you could just use Yjs 's `toJSON()` for logging / debugging. **JSON is ubiquitous**, nearly every open source project in every language uses it as the encoding for transport / state. 

I am working with a new Text Editing framework that gives its state as a JSON. If I have to use Yjs here I will constantly be converting the JSON to Yjs Map / Array for every keystroke and vice versa. 

The other option is to go inside the internals of the Editor and create a provider (just like the ones for prose mirror, tiptap etc). Which is not just a pain but also I see the provider documentation isn't yet up here.

@dmonad Could you give me the simplest way forward from this situation?

**Comment by raineorshine** [comment]
> If I have to use Yjs here I will constantly be converting the JSON to Yjs Map / Array for every keystroke and vice versa.

This might in fact be the best move here. You could probably develop an intermediate representation that allows you to efficiently map changes from the JSON state to the Yjs state without having to re-parse the entire structure every time. While not as efficient as using Yjs types directly, it could still be adequately performant, and would allow a wide variety of other tools to integrate with Yjs.

**Comment by dmonad** [comment]
The original question was about representing the CRDT updates in a JSON representation for logging purposes. I provided functions to convert updates to a JSON format for debugging. However, most people won't be able to understand the generated state changes as one would need to understand how the CRDT works. Even then, it is basically impossible to read useful data out of them as they are only useful for debugging a CRDT. You always need to apply updates to a Yjs document (or Yrs,Ypy, ..). 

I still don't understand why one would want to transport state-changes in a JSON format. You really should transport the binary data instead. At least convert it to base64. JSON is simply not something you should do here.. As I explained, updates will never be human-readable.

There are still so many projects that transport the Yjs updates as a JSON Array (instead of using base64) which makes me sad. So many wasted bytes... :cry:  So I can't stress this enough. Never ever transport Yjs updates as-is in a JSON object. Use base64 if you must. [See the documentation](https://docs.yjs.dev/api/document-updates#example-base64-encoding)

@raineorshine @gaurav21r Yes, you can definitely map the Yjs state to a JSON(-like) object. I recommend [SyncedStore](https://syncedstore.org/) or alternatives listed in the readme or the forum.

Mapping CRDT state to a JSON object is out of scope for the Yjs package. This should be provided by a separate module.

**Comment by streamich** [comment]
FWIW, wanted to post an update on JSON format. `json-joy` JSON CRDT implementation supports three encoding formats: (1) binary; (2) compact JSON; and (3) verbose JSON.

You can play with [JSON CRDT](https://jsonjoy.com/specs/json-crdt) documents in this [Playground](https://jsonjoy.com/playground/json-crdt-explorer) and see how the different formats are implemented:

![image](https://github.com/user-attachments/assets/bae25c7f-880c-4e12-845a-9a7b1a939385)
