### ISSUE TITLE
YText does not merge correctly

### ISSUE THREAD

**Issue by evilfant** [yjs/yjs#307]
**Describe the bug**
YText does not merge correctly in a certain sequence of actions

**To Reproduce**
I've found a reproducible sequence of action that cause the wrong result
It reproduces since v13.3.0 ([codesandbox v13.3.0](https://codesandbox.io/s/yjs-bug-1330-ni3uo), [codesandbox v13.5.8](https://codesandbox.io/s/yjs-bug-1358-ixjv9))
But it works at v13.2.0

1. Open codesandbox ([codesandbox v13.3.0](https://codesandbox.io/s/yjs-bug-1330-ni3uo) or [codesandbox v13.5.8](https://codesandbox.io/s/yjs-bug-1358-ixjv9))
2. Open console
3. Loot at "Resulting strings:"

**Expected behavior**
It should be `Resulting strings: a_sda a_sda`, but it is `Resulting strings: da_sa da_sa`

**Environment Information**
 - I reproduced it in Crome, nodejs 12.18.1 and codesandbox (not sure about version)
 - Yjs v13.3.0 - v13.5.8

**Comment by dmonad** [comment]
Hi @evilfant,

thanks for finding this issue and providing a very helpful codesandbox!

The issue only happens when you apply document updates as "local updates". The issue issue doesn't happen when you change your `updateDoc` function to: 

```js
const updateDoc = (doc, update) => {
  applyUpdate(transaction.doc, update, transaction.origin);
};
```

The providers usually just do `Y.applyUpdate`, or create an explicit "remote transaction". I didn't account for this case.

Remote transactions often apply additional computation, like updating search markers that are required for finding the correct position in sublinear time. In your example, the Yjs docs were actually synced correctly. But the content was inserted at the wrong position.

Thanks for finding this issue. I fixed this issue in v13.5.9 by forcing that all transactions that apply remote document updates are marked as remote transactions. This brings up the question whether it is safe to mix remote and local changes in a syngle transaction. Please avoid doing:

```js
doc.transact(() => {
  // remote change
  Y.applyUpdate(doc, update)
  // local change
  doc.getText().insert(..)
})
```
