### ISSUE TITLE
Error: array length exceeded

### ISSUE THREAD

**Issue by georeith** [yjs/yjs#314]
**Checklist**

* [x] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [x] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**
We're getting the error: `Error: array length exceeded` when trying to delete an element in a `Y.Array`.

**To Reproduce**
I have made a reproduction here, as you can see the `Y.Array` has length 5 but won't allow us to delete the last item.
https://codesandbox.io/s/elastic-lalande-vrjcu?file=/src/index.js:0-690

**Expected behavior**
The last item should be deleted.

**Environment Information**
 - Chrome
 - 13.5.10

**Comment by dmonad** [comment]
Hey @georeith, 

There was a complex assemble of issues that lead to `next.insert(5, ['rectangle2'])` to now throw an array-length exceeded exception.  


```js
  doc.transact(() => {
    next.insert(0, ['group2'])
  })
  doc.transact(() => {
    next.insert(1, ['rectangle3'])
  })
  doc.transact(() => {
    next.delete(0)
    next.insert(0, ['rectangle3'])
  })
  next.delete(1)
  doc.transact(() => {
    next.insert(1, ['ellipse4'])
  })
  doc.transact(() => {
    next.insert(2, ['ellipse3'])
  })
  doc.transact(() => {
    next.insert(3, ['ellipse2'])
  })
  doc.transact(() => {
    doc.transact(() => {
      // this should have failed because the length of the array is 4
      next.insert(5, ['rectangle2'])
      // instead this should have been
      // next.insert(4, ['rectangle2'])
    })
    doc.transact(() => {
      next.delete(4)
    })
  })
```

So basically there was a bug in your code (because the position you try to insert does not exist). But Yjs did fail to throw an error and then updated the internal state incorrectly. This is now fixed  - you get a proper error message.

Btw, since this might not be obvious: Yjs throws an exception when you try to insert at a position that does not exist.

While this is completely fine: 

```js
const array = []
array[7] = 'new'
```

Yjs doesn't allow this type of behavior:

```js
yarray.insert(yarray.length + 1, ['new']) // throws an exception
```
