### ISSUE TITLE
Include an isLocal indicator in the 'update' callback

### ISSUE THREAD

**Issue by Flamenco** [yjs/yjs#321]
**Is your feature request related to a problem? Please describe.**
I find myself having to check every update for an origin.  Most of the time i do this to prevent cycles and redundant packets.

**Describe the solution you'd like**
It would be helpful if the API included an 'isLocal' property to indicate the update came from the data type's document locally, whether or not the origin was set in the transaction.

**Describe alternatives you've considered**
The workaround is to use the same origin throughout the client.  It is tedious and error prone.

```javascript
yText.on('update', ( change, origin, isLocal ) =>{
  if (isLocal) {
    // notify peers
  }
})

// Even better, use an object for future extensibility

yText.on('update', (change, origin, {isLocal} ) =>{
  if (isLocal) {
    // notify peers
  }
})

// Still, even better for the daring and next major version

yText.on('update', (change, {origin, isLocal} ) =>{
  if (isLocal) {
    // notify peers
  }
})

```

This would clean up a use case such as this: 
```javascript
doc1.on('update', (update, origin, isLocal) => {
  if (isLocal) {
     Y.applyUpdate(doc2, update)
  } 
})

doc2.on('update', (update, origin, isLocal) => {
  if (isLocal) {
     Y.applyUpdate(doc1, update)
  } 
})

doc1.getArray('myarray').insert(0, ['Hello doc2, you got this?'])
```

**Comment by Flamenco** [comment]
One other thought is if the update object contains the document source, we could also just compare that to the doc in question, either as the solution, or a workaround to the convenience parameter.

**Comment by dmonad** [comment]
Hi @Flamenco,

This concept is flawed because providers should work well together with other providers. Your suggestion only forwards updates that are applied to the local document. If the websocket provider applies an update (`isRemote=true`) it should be forwarded through your custom provider as well. I recommend working with the origin instead.

```js
class Provider {
  constructor (ydoc) {
    ydoc.on('update', (update, origin) => {
      if (origin !== this) { // ignore updates applied by this provider
        // this update was produced either locally, or by another provider. 
        sendUpdate(update)
      }
    })
   // listen to an event that fires when a remote update is received
   this.on('update', update => {
     Y.applyUpdate(this.ydoc, update, this) // the third parameter sets the transaction-origin
   })
  }
}
```

FYI: all transactions already have a `isRemote` property that basically does what you were looking for. But, as said, I recommend to work with origins instead.

**Comment by Flamenco** [comment]
I did not see the `isRemote`. Thank you for pointing it out.

So per the example, every update will be resent again by every client.  Correct?  And doing so will also propagate a multiple provider mesh at the cost of being redundant on one of the providers?

**Comment by dmonad** [comment]
When a provider applies an update, it will ignore the `update` event that `ydoc` fires. So the document update won't be sent again.

If you have two providers, the second provider will pick up on the document update and send it again to all clients. It is not expected that both providers connect to the same clients (e.g. you could have a network and a database provider). If you use two network providers that connect to the same clients (e.g. a y-websocket and a y-webrtc provider using the same room-name), then yes, you will send every document through both providers.

**Comment by Flamenco** [comment]
> When a provider applies an update, it will ignore the update event that ydoc fires. So the document update won't be sent again.

@dmonad, is that for the example you provided with the guards, or in general?

My motivation for this was that I created a pretty brutal stress test for Y, where I create 100 documents, and then create 1000 clients using those 100 documents, then make 1000 random changes from random clients within a few seconds;  Finally verify all clients are in sync.  The multiple network packets obviously start to add up exponentially in this case

On top of this, my provider uses a single websocket connection for all documents, instead of a separate endpoint for each.  I was able to work out maintaining binary updates for multiple documents using a single endpoint.  Its working really well, as long as I can eliminate redundant packets.   So if my provider can know if it is the only provider, I might be able to make some assumptions and optimize, and if not the only provider, emit the duplicate updates.

**Comment by dmonad** [comment]
Yjs doesn't emit duplicate updates. If you apply a certain update twice to a document, it will only emit one update event.

You can implement this stress test efficiently using the above approach. I don't see why there might be redundant updates.

Example: Document A creates an update. Your provider listens to the update event, transmits the update through the network, and then applies it to each document individually:

```js
Y.applyUpdate(this.ydoc, update, provider)
```

All documents will fire an update event. But there is no need to forward this update event to other clients. So you simply filter this event because it originates from the same provider.

```js
ydoc.on('update', (update, origin) => {
      if (origin !== this) { // ignore updates applied by this provider
        // this update was produced either locally, or by another provider. 
        sendUpdate(update)
      }
    })
```

Btw, Yjs has a simulation framework that does what you are describing. The only difference is that the simulation framework mocks the network protocol. Furthermore, the simulation framework mimicks cases like..

* the client disconnects / reconnects from the network
* the client is offline
* random network delays

I use this framework for testing the correctness and of course also performance.

**Comment by Flamenco** [comment]
I think the confusion is that i did not use a provider specifically.  I simply followed the example in the docs, as such:

```javascript
doc1.on('update', (update) => {
     Y.applyUpdate(doc2, update)
     sendUpdateToServer(update)  
})
```

This is why I commented on the doc site, in order to clarify this condition.

**Comment by dmonad** [comment]
So you are suggesting to add the origin to the example? You might be right, but I try to keep the examples minimal. I assume that the developer will ask the same question (what about duplicates?) and figure out a solution. The described approach above is not the only one. Most people simply use a boolean flag. Until recently, I used the lib0/mutex approach (not worth explaining here).

**Comment by Flamenco** [comment]
I can appreciate the idea of simplicity.  At the same time as a newbie, here are the items that are ambiguous to me.

1. When modifying a type outside of a transaction, a default value is used for the wrapped transaction.
2. The transaction ID may not be the same for the same document if the developer uses different origins by intent or mistake, or by not providing one at all.
3. The origin seems to not be one and the same with the fact that an update callback is fired from the documents own member locally,  or from an external source.
4. The update received is a binary object;  only the origin is provided in the API

So it just seems logical that this flag would be available in some kind of context, independent of the developer provided origin.
