### ISSUE TITLE
How to transfer the undomanager to a copied type?

### ISSUE THREAD

**Issue by echarles** [yjs/yjs#328]
Hi, for https://github.com/jupyterlab/jupyterlab/pull/10949 we need to transfer an existing undomanager to a new cloned yjs document (to ensure the user is able to undo his previous visual history).

Any advice on this?

**Comment by dmonad** [comment]
Hi Eric!,

I think you want to transfer the undo-history to a cloned shared type, not a cloned Yjs document. The latter is possible, the former is not.

The UndoManager tracks a scoped history on the Yjs document. E.g. you can track the history of a shared type and reverse certain operations that you performed. However, in Jupyterlab we clone (**) a type to a different location without tracking its history. Yjs doesn't know that this type existed before and thinks it is a new insertion. Since the Y.UndoManager works directly on the CRDT history, we can't translate the undo-history to a new type.

(**) "cloning a type" usually means that we create a new shared type with the same content. It does not share the same history.

I'm closing this issue. But please feel free to continue discussing here on in the linked issue.
