### ISSUE TITLE
Y.Text content gets duplicated when multiple clients are changing the whole value

### ISSUE THREAD

**Issue by ionutpasca** [yjs/yjs#364]
**Checklist**

* [x] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [ ] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**
We're using yjs together with [y-monaco](y-monaco) and  [y-websocket ](https://github.com/yjs/y-websocket) in order to create a replication of vscode. As we need a really close experience with the tool, at every save, we are running prettier over the content of the editor and replacing the whole value if we notice something is different. It was observed that in some cases, when other clients are connecting to that document, or if they run prettier (replace the content) in the same time, the content gets duplicated.

In order to replicate the file hierarchy, we are using a singe Y.Doc, that contains a map with an Y.Text for each file.

**To Reproduce**
1. Go to ['official Yjs page / collaborative editor'](https://docs.yjs.dev/getting-started/a-collaborative-editor)
2. At the bottom of the page you can play with a real-time-collaboration editor
3. Add an interval that replaces the content at every 500ms (in both editors)
4. Try to write something in one of the editors, while the replacement takes place

**Expected behavior**
At every 500ms, the content should be only the value set at step 3.

**Screenshots**

**Environment Information**
 - Browser: Chrome - Version 92.0.4515.131 (Official Build) (64-bit)
 - NodeJS: v16.13.0
 - Yjs: ^13.5.23
 - y-monaco: latest
 - y-websocket: latest

**Additional context**
We are using the following code in order o replace the content:
`const textContent = ytext.toString();`
 ` ytext.applyDelta([{ delete: textContent.length }, { insert: <value_here> }]);
`

------------

What I could notice in the cases in which the content got duplicated was that inside **monaco-binding library -> ytextObserver**, instead of:
- **delete -> insert**,
we have:
- **delete -> insert -> insert**

Please notice them in the following screens:
![monaco-binding-logs](https://user-images.githubusercontent.com/11486739/146478777-6948100d-4130-46e5-b77b-1f32f8b09c1d.png)

![details_about_evens](https://user-images.githubusercontent.com/11486739/146478815-139f6caa-2963-4620-b0c1-b43d8c31565c.png)

I'm attaching a video as well:

https://user-images.githubusercontent.com/11486739/146478933-4322340e-988f-4534-bb1e-396168d10675.mp4

**Comment by paulbrie** [comment]
Hi @dmonad! Sorry to insist but we're blocked. Can you please give us an update about this ticket. Any response would be appreciated. 🙏

**Comment by dmonad** [comment]
@paulbrie It's completely fine for sponsors to mention me when they need an issue/question answered. It's hard for me to keep track of the sponsors, so simply mention me from a sponsor account and I'll answer shortly.

Thanks for the nice issue description @ionutpasca. I feel like I already answered this one in the discussion board.

This behavior is expected. If two clients delete the same content at the same time, then we can't delete the same content twice. You expect to end up with empty content anyway. When two users insert something at the same time, we would end up with two insertions. Even if the insertions contain the same content.

Now, when we have two clients replacing the same content at the same time (`delete` • `insert` x 2), then we naturally end up with duplicated content. There is no algorithm (based on CRDTs) that can magically resolve the merge to be the expected result. This is just something you have to deal with by expressing your intend differently.

One solution might be to replace the whole Y.Text every time you run prettier. If two users concurrently run prettier, one replacement will win and everyone will end up with the same content. The drawback is that all users lose their selections and that concurrent edits no longer converge (imagine a user inserting a type fix concurrently, then this change will be discarded because it belongs to the replaced Y.text). E.g. `ymap.set('editor', new Y.Text(replacedContent))` every time you run prettier.

A better solution is to run prettier only on a single instance. The central server (if there is any) could run prettier or you could create some kind of locking mechanism (although there is no good locking mechanism for clients). If you go this route, please make sure to only apply the differences to the Y.Text. If you do a replacement, you lose some of the semantics and users might end up with weird merge results.

My recommendation is to go with a central server to run prettier.
