### ISSUE TITLE
Y.logUpdate, but returning a plain object

### ISSUE THREAD

**Issue by holtwick** [yjs/yjs#395]
Y.logUpdate() is very useful, but it logs directly using its own representation.

I am currently working on a financial app, where it would be beneficial, if the full information of updates would be known and could be dumped into a protocol / listing for human verification. 

Looking at the implementation of Y.logUpdate() I learn it is quite easy to accomplish for myself. But it might be a nice addition to Yjs to increase trust into the protocol and help to understand the internal mechanics easier for people that are interested in the magic of CRDT :)

**Comment by alderzhang** [comment]
Y.decodeUpdate may solve your problem.

**Comment by dmonad** [comment]
@ankon 
Wow, this is creative :smile: 


---

@holtwick 
I'm closing this because I feel this is addressed by `Y.decodeUpdate`. But let me know if you have further suggestions.

**Comment by holtwick** [comment]
Well, thanks for the feedback. Maybe I need something different at all. Let's take the following example:

```ts
let doc = new Y.Doc()
let items = doc.getArray("items")
items.push([
  new Y.Map(
    Object.entries({
      id: "a",
      title: "A",
    })
  ),
])
let item: any = items.get(0)
item.set("title", "AB")
```

I'd rather be interested in information like:

1. APPENDS {id:'a', title: 'A'} TO doc.items 
2. SETS title='AB' AT doc.items[0]

I understand, this is probably something that is closer to `applyUpdate` than the update data itself. How could I best achieve this?

**Comment by dmonad** [comment]
Information, as you described, could be provided by reading the items (see the content property, and the parent property). However, we would not know whether the changes would eventually succeed (they could be overridden by a concurrent local change). Furthermore, we can't provide this kind of information for list items.

Due to the complexity of this feature (even in a limited scope) I definitely won't implement this in the near future.

A solution to this would be to apply the update to the document to see the changes. If you don't want to apply the changes yet, I suggest that you create a temporary document and listen to the changes (using the `observeDeep` method).

**Comment by holtwick** [comment]
Thanks, that helps!
