### ISSUE TITLE
Y.applyUpdateV2 doesn't seem to handle Skip type data correctly

### ISSUE THREAD

**Issue by alderzhang** [yjs/yjs#406]
After using `Y.mergeUpdateV2` to merge the update, some `Skip` type data will appear, and then use the `Y.applyUpdateV2` to apply the update. It seems that `integrateStructs` method does not process the `Skip` type data correctly, resulting in some data being in the pending state forever.

**To Reproduce**
1. Download and unzip `test.zip`, load Uint8Array from `test.json` as variable `temp1`
[test.zip](https://github.com/yjs/yjs/files/8302963/test.zip)
3. Run code:
``` javascript
const decoded = Y.decodeUpdateV2(temp1);
console.log(decoded.structs[270]);

const doc = new Y.Doc();
Y.applyUpdateV2(doc, temp1);
console.log(doc.store);
```
4. On console, `decoded.structs[270]` is a `Skip` type data, `id` is `client: 3769453340, clock: 270`, `length` is `2`:
<img width="311" alt="image" src="https://user-images.githubusercontent.com/8778642/158995512-703a5ca4-9d2b-4784-8dcd-c4dcc91f0cf3.png">

5. `doc.store.pendingStructs.missing` has a record `3769453340 => 271`, therefore some update is on pending state:
<img width="459" alt="image" src="https://user-images.githubusercontent.com/8778642/158996118-430c7820-256c-4e94-897a-98cfe622d30b.png">

**Expected behavior**
If my understanding is correct, `Skip` type data means that there is an item hear, but it has been deleted. So it should not be recognized as missing data.

**Environment Information**
 - Yjs version: 13.5.28

**Additional context**
`integrateStructs` method looks like it skips the processing of Skip type data directly. Is this an exception?

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/8778642/158998197-0cc6a95e-803c-46db-b3f6-bf4c2a0a785e.png">

**Comment by dmonad** [comment]
Hi @alderzhang,

In Yjs, there are three types of structs encoded in document updates. An `Item` contains content. A `GC` refers to deleted content that is stripped from metadata (part of the memory optimization). A `Skip` refers to a missing struct. 

Skips are necessary to refer to missing content. We use them as placeholders until the actual data arrives. The idea is that eventually the missing content arrives and the other data can be applied.

I'll close this issue because I think Yjs handles this case correctly. But feel free to comment further if you have follow-up questions.

**Comment by alderzhang** [comment]
Thanks for your reply！

It seems that I need to learn more Yjs internal implementation, I think maybe some update is missing when calling the `Y.mergeUpdateV2` method, I will find a way to confirm this.
