### ISSUE TITLE
Add 'stack-item-changed' event

### ISSUE THREAD

**Issue by BitPhinix** [yjs/yjs#407]
Slate-yjs relied on the `stack-item-added` even being fired each time something is pushed to the undo stack in order to store the selection after the change to properly restore it on redo.

Ever since https://github.com/yjs/yjs/commit/931a37a331b48448679e004342e8dc41fb580d75 `stack-item-added` is only called for the first change being added to the undo stack item, thus the redo selection is never updated and incorrect if a stack item contains more than one change.

I don't think there is currently a way to detect changes being added to stack items, only the addition of stack items themselves. My proposal would be to add an additional `stack-item-changed` event which is called if changes are added to existing stack items.

I'm sure this behaviour change broke other editor bindings as well

**Comment by dmonad** [comment]
That makes sense. I added a `stack-item-updated` event that is fired when an existing stack item is updated.

However, generally, you want to restore the selection that was active before the stack-item was added. Therefore, it is undesirable to fire the event when an item is only updated (because you are overwriting an existing stored selection). I felt the previous implementation was incorrect and I fixed it. With the addition `stack-item-updated` you should be able to implement either behavior.

I just got that into the next release (will publish in a bit).

**Comment by BitPhinix** [comment]
Awesome, thanks 🙏
