### ISSUE TITLE
An easy way to know if two documents are in sync (including their internal state)

### ISSUE THREAD

**Issue by almosnow** [yjs/yjs#419]
Hi,

I use YJS extensively to sync documents between many nodes connected together using websockets through a central server. In order to avoid repeating many of the updates messages, I put together a dynamic where nodes only get updates using state vectors and it works quite nice.

But, there's a lot of situations where a new node comes up and I don't know if it's up to date or not, so I basically force it to do a "full sync" to put it in words. Even if the contents of the document are the same, I still have to do this because the internal state (clocks, etc) may not be up to date.

It would be nice if there was a way to know if two documents are already in the same state (by comparing state vectors perhaps), so that a round trip with all the data could be avoided.

Thanks and props to this awesome project!

**Comment by dmonad** [comment]
You could compare `snapshots` (e.g. `Y.snapshot(ydoc)`) - or even better - compute the hash of the snapshot and compare that.

FYI: That will not always work because the snapshot encodes client-ids in the order in which they received the client-ids. A solution would be to order client-ids before encoding them. But it will work in almost all cases.

Feel free to open another feature request to make snapshots comparable. However, it will be low priority for me right now.
