### ISSUE TITLE
Correctness issues due to tombstone garbage collection after a fixed time period

### ISSUE THREAD

**Issue by Zombobot1** [yjs/yjs#428]
I read this [paper](https://dl.acm.org/doi/pdf/10.1145/3392825) and it claims this:

> Yjs variations incurred correctness issues (e.g. a tombstone is collected as garbage "after a fixed time period" [40], which is clearly incorrect) due to the intricacies in maintaining tombstones and neighboring objects under complex concurrent scenarios 

I tried to search on the forum and in the issues, but I only found this issue #193

I guess it is already fixed. I want to create this issue for history to avoid scaring away potential users who read that paper.

**Comment by dmonad** [comment]
Thanks for bringing this up. With all respect for what he has done, Chengzheng Sun has been quite ignorant of the advancements in the CRDT space.

As I described in the paper, the mentioned approach was experimental and needed more investigation. But it did work under the mentioned constraints. The experimental implementation was not general-purpose only added as an optional feature for some of our network providers for Yjs.

I told him in previous emails that Yjs does not employ the mentioned garbage-collection approach anymore. It was removed in 2017.

Most importantly, there was no indication that this approach was still used in 2019/2020, when he published the paper. He simply needed to take a look at our homepage.

Another comment from him:

> Work on extending CRDT for rich text co-editing, e.g. the Yjs extension, was intended to address this
limitation, but still in early stages of development - https://arxiv.org/pdf/1905.01517.pdf

Even predating his paper, Yjs has been used in practice by several companies for rich-text editing with the Quill editor. The first company that used Yjs in practice was Pluxbox Radiomanager in 2017. This was clear from the list of sponsors and the mention of "Companies that use Yjs".  Furthermore, I advertised Yjs as "production-ready" back then, as I was making my income as a contractor integrating Yjs into existing products.

The CRDT community has always been fair against the predating research on OT. So I feel Sun is fighting against windmills in his series about defending his OT research. Don't take his arguments against CRDTs too seriously. There are valid arguments to use CRDTs over OT that researchers in the space are bringing up. This doesn't mean that CRDTs are superior in every way. Nobody is saying that. Furthermore, there are solid CRDT implementations that can be used in practice - and Yjs is definitely one of them.

I'm closing this issue because I can't take action on this issue. Feel free to discuss this further in discuss.yjs.dev.
