### ISSUE TITLE
Yjs was already imported.

### ISSUE THREAD

**Issue by dmonad** [yjs/yjs#438]
I created this ticket as a reference for all users experiencing the following error message:

> Yjs was already imported. This breaks constructor checks and will lead to issues!

Please take this seriously.

If you see this message, make sure that you only import one version of Yjs. In many cases,
your package manager installs two versions of Yjs that are used by different packages within your project.
Another reason for this message is that some parts of your project use the commonjs version of Yjs
and others use the EcmaScript version of Yjs.

This often leads to issues that are hard to debug. We often need to perform constructor checks,
e.g. `struct instanceof GC`. If you imported different versions of Yjs, it is impossible for us to
do the constructor checks anymore - which might break the CRDT algorithm.

**Comment by Himself65** [comment]
This error will always happen when using `next.js` which has server-side rendering

```
info  - Compiled successfully
info  - Collecting page data ...Yjs was already imported. This breaks constructor checks and will lead to issues! - https://github.com/yjs/yjs/issues/438
info  - Collecting page data ...Yjs was already imported. This breaks constructor checks and will lead to issues! - https://github.com/yjs/yjs/issues/438
info  - Collecting page data ..Yjs was already imported. This breaks constructor checks and will lead to issues! - https://github.com/yjs/yjs/issues/438
Yjs was already imported. This breaks constructor checks and will lead to issues! - https://github.com/yjs/yjs/issues/438
Yjs was already imported. This breaks constructor checks and will lead to issues! - https://github.com/yjs/yjs/issues/438
info  - Collecting page data ...Yjs was already imported. This breaks constructor checks and will lead to issues! - https://github.com/yjs/yjs/issues/438
Yjs was already imported. This breaks constructor checks and will lead to issues! - https://github.com/yjs/yjs/issues/438
info  - Collecting page data  
info  - Generating static pages (7/7)
info  - Finalizing page optimization  
```

**Comment by Hypercoded** [comment]
> This error will always happen when using `next.js` which has server-side rendering
> 
> ```
> info  - Compiled successfully
> info  - Collecting page data ...Yjs was already imported. This breaks constructor checks and will lead to issues! - https://github.com/yjs/yjs/issues/438
> info  - Collecting page data ...Yjs was already imported. This breaks constructor checks and will lead to issues! - https://github.com/yjs/yjs/issues/438
> info  - Collecting page data ..Yjs was already imported. This breaks constructor checks and will lead to issues! - https://github.com/yjs/yjs/issues/438
> Yjs was already imported. This breaks constructor checks and will lead to issues! - https://github.com/yjs/yjs/issues/438
> Yjs was already imported. This breaks constructor checks and will lead to issues! - https://github.com/yjs/yjs/issues/438
> info  - Collecting page data ...Yjs was already imported. This breaks constructor checks and will lead to issues! - https://github.com/yjs/yjs/issues/438
> Yjs was already imported. This breaks constructor checks and will lead to issues! - https://github.com/yjs/yjs/issues/438
> info  - Collecting page data  
> info  - Generating static pages (7/7)
> info  - Finalizing page optimization  
> ```

Is there a fix/workaround for this on Next.js?

**Comment by ryantan** [comment]
@Hypercoded  Wrap the component importing yjs in `dynamic`, assuming `ComponentA` imports yjs:

```
import dynamic from 'next/dynamic';

export const ComponentANoSsr = dynamic(() => import('./ComponentA'), {
  ssr: false,
});

```

**Comment by mrdrogdrog** [comment]
We have this error a lot. Especially in renovate update pull requests. Check your yarn.lock oder package-lock.json for multiple entries! Eventually you have to regenerate the lock file or edit it manually. You must NOT have more than one entry!

**Comment by zanemcca** [comment]
@dmonad do you have a recommended workaround when this error is the result of both the esm and cjs versions of yjs being initialized?

**Comment by dmonad** [comment]
@zanemcca First of all, please realize how crazy it is that your bundling setup requires both the cjs and the esm version of a package. This doubles the bundle size shipped to the client. The javascript engine will have trouble optimizing the code. This is not normal. There is not a single reason why one should do this. This is a bug. You should fix it. Not just the warning message in Yjs. Fix your bundling process! If you started with a template of your favorite bundler, let them know that there is a bug!

A lot of people experience this issue with webpack. I don't understand why webpack is so hyped. It's full of weird issues like this. The whole bundling process seems way too random and magical to me. Sometimes it just works. You're mostly screwed when it doesn't. I'd rather have a working bundler than using webpack with its myriad of weird, non-standard extensions that don't exist in other (better) bundlers.

Something that helped me is to [set an alias](https://webpack.js.org/configuration/resolve/#resolvealias) in webpack. This forces webpack to use a specific installation whenever it sees `require('yjs')` or `import 'yjs'`.

Sorry for my rant. But this needed to be said. I'm sure you just started with one of the "recommended" setups and now have to fix this weird issue. This is not your fault. This is an issue with webpack or whatever bundler you are using. Sane bundlers (e.g. rollup) are overall easier to work with than insane bundlers (webpack) that only focus on implementing the next big feature.

**Comment by zanemcca** [comment]
No apology needed at all @dmonad. You are preaching to the choir. We are indeed using webpack and it started off from a pretty boilerplate solution that can be found anywhere online. The alias workaround you recommended was the exact solution we needed to get it to behave properly.

For others who might run into this the exact reason we ran into this issue is because we have a few layers of libraries, `editor-core` and `editor-react`. The `editor-core` is built with a few runs of tsc to build both ESM and cjs. The `editor-react` however is only built to cjs since webpack does not support building to esm.

Our application level webpack uses cjs for anything that touches `editor-react` and it uses esm for anything directly from `editor-core`. We tried to just re-export everything from `editor-core` in `editor-react` to entice webpack to use only cjs but that only resolved the highest level of the problem. Ultimately the alias solution was the only thing that worked.

Knowing what I know now I would say that using webpack to build `editor-react` is the ultimate source of this problem. Transitioning to a better build system that supports esm outputs would likely resolve the issue even if we kept using webpack to build our main application. It is somewhat ironic that the problem is because Webpack does not play nice with nested webpack builds.

**Comment by tantaman** [comment]
This problem is often caused by these lines in the yjs package.json:

https://github.com/tantaman/yjs/blob/afc6728c9ea2560e6af04b963eec9020c5d02f34/package.json#L30-L31

```
"exports": {
    ".": {
      ...
      "import": "./dist/yjs.mjs",
      "require": "./dist/yjs.cjs"
    }
}
```

and having one dependency in your project that does `require('yjs')` and another that does `import 'yjs'`

Those lines are redundant given the presence of https://github.com/tantaman/yjs/blob/afc6728c9ea2560e6af04b963eec9020c5d02f34/package.json#L5-L6

If only these lines https://github.com/tantaman/yjs/blob/afc6728c9ea2560e6af04b963eec9020c5d02f34/package.json#L5-L6 were present, and the `exports` version removed, then `esbuild` based tools would properly package yjs and remove duplicates.

See: https://github.com/evanw/esbuild/issues/1950

The presence of 

```
"exports": {
    ".": {
      ...
      "import": "./dist/yjs.mjs",
      "require": "./dist/yjs.cjs"
    }
}
```

prevents esbuild based tools from de-duping `require('yjs')` and `import 'yjs'` uses in the same project.

**Comment by dmonad** [comment]
This is not a solution @tantaman.  You are effectively proposing to make Yjs a commonjs module and remove the much better ESM bundle.

The `module` field is actually only used by a few older bundlers and has no effect otherwise (not a spec). Removing the `exports`  field would effectively make Yjs a commonjs bundle. Neither esbuild, webpack, nor rollup use the "module" version by default anymore. They converged on the `exports` field which is a spec that I should be allowed to use in Yjs (too bad that the spec is confusing esbuild..).

I prefer ESM in my projects. It can be bundled more efficiently. It enables tree-shaking. ESM is awesome. CJS is a problematic beast from the past. It's fine if you use it. But eventually, we need to progress to a brighter future (which will be ESM).

I want to reiterate that it doesn't make sense to bundle the same module twice. If it happens with Yjs, it likely happens with other packages you import as well. Why would you so readily accept that packages are imported twice? If I were you, I'd fix that. This is not a bug in Yjs. Try to only use `require('module')` or only use `import 'module'` in your project.

**Comment by tantaman** [comment]
It’s a problem of transitive dependencies. if you use import in your
project but a package you depend on (or one it depends on) uses require you
hit this issue.

And this change wouldn’t  force usage of cjs, esm would still be respected
— but that is for a more detailed response.

**Comment by tantaman** [comment]
> too bad that the spec is confusing esbuild

I wish that were the case. esbuild implements the spec faithfully which I’m
told says thou shall not replace a cjs with an mjs when require is used.

Would you ever consider making yjs esm only?

**Comment by dmonad** [comment]
> Unfortunately it’s a problem of transitive dependencies. 

Then it's a problem with your transitive dependencies; still not with Yjs. Try to make your transitive dependencies export a cjs & mjs module. That's what the `exports` field is for.. Doing this would also make your build smaller because Yjs is probably not the only dependency that you bundle twice for no reason.

I won't remove the cjs bundle either because then a bunch of other people would jump at me.

Exporting different versions of a package for different environments (module, exports, browser, ..) should be allowed. It's a really cool feature that I'm using extensively. I'm just using a feature correctly. Either you need to fix your build setup, or your favorite bundler needs to add an option to do the sane thing and not bundle the same module twice. I'm not sure what kind of "spec" you are talking about (bundlers have no spec.. everyone just does whatever they like..), but bundling the same module twice can't be reasonable for browser builds. It should fail with an exception. Rollup, for example, does the reasonable thing here and only bundles one version of a package..

I'm tired of discussing this. I'm sorry, but I can't help you. I added a lot of advice in this thread. I probably won't answer again unless there is a reasonable proposal that doesn't remove an existing feature.

**Comment by evanw** [comment]
Author of esbuild here. 

The [`exports` algorithm specification](https://nodejs.org/api/esm.html#resolver-algorithm-specification) is quite rigid about the `import` and `require` conditions and mandates [dual-package hazard](https://nodejs.org/api/packages.html#dual-package-hazard) behavior *by design*, so it’s not some bug that esbuild needs to fix. It’s actually what’s supposed to happen when you use `exports` this way. Writing a dual CommonJS/ESM package using `imports` and `require` that can’t handle both versions being imported simultaneously is unambiguously a design problem with the package. So I believe you are using this feature incorrectly. 

What bundlers have to offer to get around this required behavior is that they (at least Webpack and esbuild) automatically enable a bundler-specific `exports` condition called `module` (unrelated to the `main` field with the same name). This is enabled regardless of whether a package is imported using an `import` statement or a `require` call, so it means bundlers will *always* pick it and your package won’t end up being double-imported. Node doesn’t ever enable the `module` condition, so if you only provide one alternative for node (such as the `default` condition) then node also won’t ever double-import your package. So the recommendation would be to do something like this instead:

```json

"exports": {
  ".": {
    ...
    "module": "./dist/yjs.mjs",
    "default": "./dist/yjs.cjs"
  }
}
```

This is all documented on esbuild’s website here: https://esbuild.github.io/api/#how-conditions-work. You are welcome to either follow this advice or not. It’s up to you. I just thought that it could be useful to hear about this issue from a bundler’s perspective.

**Comment by tantaman** [comment]
Brilliant. I think this solves the issue from all three perspectives 
- bundler
- library provider
- & consumers

**Comment by Himself65** [comment]
For someone who wanna figure out why this happened. You can check the `lock.json` file to see whether other dependencies use another instance of yjs

Related: https://github.com/toeverything/blocksuite/commit/0132afab49c80ae164b607561232208d87e4e3a5#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL4176-L4178

**Comment by dmonad** [comment]
Thank you for chiming in @evanw. I didn't know about the `exports.module` field. I only knew `module` as a field that existed next to the `main` field before `exports` emerged. This helps immensely. I will add that to my packages.

> Writing a dual CommonJS/ESM package using imports and require that can’t handle both versions being imported simultaneously is unambiguously a design problem with the package

  I won't go into detail, but it is not possible (without significant tradeoffs) to avoid constructor checks in Yjs. That's why the warning message in Yjs exists. In a better world, all packages would be able to perform constructor checks of `peerDependencies`. They are quite useful.

 I stand by my point that it is insane to bundle the same package twice for browsers.

  Think about @tantaman's setup. He probably bundles several modules twice because of his multi-layer bundling process. Yjs is just the only one that throws a warning. That can't be what we want.

  > @evanw [in the mentioned thread](https://github.com/evanw/esbuild/issues/1950#issuecomment-1018819970): [This] is the unfortunate result of a set of conventions that have been created and adopted by the community.

Not all bundlers follow this insane practice to bundle the same module several times. You would be absolutely capable to..

  1. .. throw warning messages when the same package is bundled twice. Because why would anyone ever want to do that? They should know..
  2. .. add an option to prefer a specific version. This is what rollup does - [see "exportConditions" & "mainFields"](https://www.npmjs.com/package/@rollup/plugin-node-resolve)
  3. .. reduce the bundle size of your users significantly by implementing 1. and 2. You can still provide the "node" behavior as an "insane" option like rollup does.

It's good that there is an `exports.module` field. But apparently, not everyone knows about this. Furthermore, not all bundlers implement this behavior. I prefer to be verbose about these problems instead of hiding them under the carpet.  That's why I hope that bundlers throw at least a warning message, so I don't have to do that..

**Comment by srsudar** [comment]
I also saw this error and determined it was due to server-side rendering. I have a component called `<Editor />` that depends on things that depend on yjs. I originally had (using react/preact) something like:

```
import Editor from './editor';

...

return (
  <>
    <OtherComponent />
    <Editor />
  </>
);
```

I resolved the error by removing the `import` altogether and changing it to:

```
// rm this line: import Editor from './editor';

...
let Editor;
if (typeof window !== 'undefined') {
  Editor = require('./editor').default;
}

return (
  <>
    <OtherComponent />
    {Editor && <Editor />}
  </>
);
```

I don't know enough about SSR and package resolution to comment on if this is a good solution or not, but it appears to have resolved the error.

**Comment by philippviereck** [comment]
I get this warning with SvelteKit. First of all, turning off SSR removes the warning, but SSR is what I'd like to use.

The code looks like this:
` .../[slug]/+page.svelte:`
```
<script lang="ts">
	import { onMount } from 'svelte';
	import type { PageData } from './$types';
	import { page } from '$app/stores';
	import { browser } from '$app/environment';

	import SupabaseProvider from '$lib/y-supabase-modified';
	import TipTap from '$lib/TipTap.svelte';

	import * as Y from 'yjs';
	import { IndexeddbPersistence } from 'y-indexeddb';

	export let data: PageData; // this is the data from the load function

	const ydoc = new Y.Doc();

	if (data.document.length > 0) Y.applyUpdate(ydoc, data.document); // update the document with the data from the database

	const frag1 = ydoc.getXmlFragment('tiptap1');
	const frag2 = ydoc.getXmlFragment('tiptap2');

	onMount(() => {
		// this runs on the client only
		new IndexeddbPersistence($page.params.slug, ydoc);

		return () => {
			// this runs when the component is destroyed
			ydoc.destroy();
			provider?.destroy();
		};
	});

	const provider = browser
		? new SupabaseProvider(ydoc, data.supabase, {
				channel: $page.params.slug,
				id: $page.params.slug,
				tableName: 'notes',
				columnName: 'document'
		  })
		: null;
</script>

<p>{$page.params.slug}</p>
<a href="/">home</a>
<p>Yjs Demo</p>
<!-- On the server this renders a "dummy" editor with HTML content compiled from the Yjs XmlFragement -->
<!-- On the client this renders a "real" interactive editor (TipTap) with the collaboration plugin using the SupabaseProvider -->
<TipTap fragment={frag1} {provider} />
<TipTap fragment={frag2} {provider} />

```
`lib/TipTap.svelte:`
```
<script lang="ts">
	import { onMount } from 'svelte';
	import { Editor } from '@tiptap/core';
	import Collaboration from '@tiptap/extension-collaboration';
	import StarterKit from '@tiptap/starter-kit';
	import CollaborationCursor from '@tiptap/extension-collaboration-cursor';
	import type { YXmlFragment } from 'yjs/dist/src/internals';
	import { Renderer } from '@cristata/prosemirror-to-html-js';


	let element: HTMLElement;
	let editor: Editor;
	export let fragment: any;
	export let provider: any;

	// [... removed helper functions for readability]
	onMount(() => {
		editor = new Editor({
			element: element,
			extensions: [
				StarterKit.configure({
					history: false
				}),
				Collaboration.configure({
					fragment: fragment
				}),
				CollaborationCursor.configure({
					provider: provider,
					user: {
						name: "demo123",
						color: "#FFFFFF"
					}
				})
			],
			content: yXmlFragmentToProsemirrorJSON(fragment),
			onTransaction: () => {
				editor = editor;
			}
		});

		return () => {
			editor.destroy();
		};
	});
	const renderer = new Renderer();
</script>

{#if editor}
	<!-- Real-->
	<button
		class="rounded w-6 h-6"
		on:click={() => editor.chain().focus().toggleHeading({ level: 1 }).run()}
		class:text-blue-500={editor.isActive('heading', { level: 1 })}
	>
		H1
	</button>

	<!-- [...]-->
{:else}
	<!-- Dummy-->
	<button class="rounded w-6 h-6"> H1 </button>
	<!-- [...]-->
{/if}

<div bind:this={element} class="reset-tailwind p-1" id="editor">
	{#if !editor}
		<div>
			<div class="ProseMirror">
				{@html renderer.render(yXmlFragmentToProsemirrorJSON(fragment))}
			</div>
		</div>
	{/if}
</div>

```

The warning logs to the Terminal (server). I assume it's due to commonJS and ESM getting both bundled or something. But I don't understand exactly if this is even a problem. (at least I didn't notice anything)

Also, I see some framework specific advice here, maybe someone knows SvelteKit

**Comment by rozek** [comment]
Arrrgh,

I just ran into this problem myself: when trying to run a simple experiment within a web browser (without explicitly building a web app for that purpose), I saw a completely unpredictable behaviour of Yjs, started writing a long bug report...until I noticed this error message on the console and clicked on the link (just for curiosity)

Thus, first of all: would it be possible to `alert` this situation when running in a browser - since not everybody may look into the console all the time. You may even explictly crash the app, which should still be better than behaving in an unpredictable way, perhaps even damaging some data...

Second: since I'm often working with "no-build environments", I needed a solution for this problem and simply bundled Yjs and all other depending modules I currently need into a single monolith which can then be safely imported.

This approach is by no means elegant and somewhat contradicts what modules were made for - but no Yjs works like a charm.

If you are interested, just look into my related [GitHub repo](https://github.com/rozek/yjs-bundle) - I'm not really proud of my approach, but it helps me going on...

**Comment by dmonad** [comment]
> Thus, first of all: would it be possible to alert this situation when running in a browser - since not everybody may look into the console all the time? 

That would kill some production apps :)
I know that production apps unfortunately ignore this warning. In a few cases, this warning can be ignored. For example, if two separate widgets use different installations (the editor widget uses a different Yjs installation than the drawing widget). 

Thanks for the repository. FYI in `yjs-bundle.ts` you could also do `export * from 'yjs'; ..` instead of exporting everything individually. Instead of using the hosted version, you could also do to `import * as Y from 'https://esm.sh/yjs'`.

**Comment by rozek** [comment]
Thank you very much for that hint - I just changed the affected lines in code

**Comment by maietta** [comment]
I setup a repo with the problem occurring:

https://github.com/maietta/svelte-lexical-mre

Still trying to pin down the exact issue.

**Comment by i-am-the-slime** [comment]
So can this be ignored in the context of SSR with NextJS or not? 
If not, what can I do about it?
I'm confused.

**Comment by dmonad** [comment]
@CedricDumont Just published a possible fix for your specific issue to y-indexeddb

**Comment by srsudar** [comment]
Is it possible that we might have multiple versions of yjs but not be seeing the `console.error()` message? We're seeing what looks like a corrupted ydoc diff, but we're not seeing the warning message (we'd seen it in the past but we fixed it).

Is there some configuration where there is still a version mismatch somehow that manifests in the same way, but that doesn't print the helpful error message?

**Comment by culli** [comment]
I didn't find anything that connected these dots in my searches.  If you're getting `Yjs was already imported` in jest tests, it's because your test code is importing yjs and your "code under test"/real code is also importing yjs. Maybe both times from disk, rather than using the cache during the first test run?

Jest seems like it does some tricks to load modules separately and cache them for the test code. For example see [resetModules](https://jestjs.io/docs/configuration#resetmodules-boolean)

For me the fix was in jest.config.js:
```
module.exports = {
  moduleNameMapper: {
    yjs: '<rootDir>/node_modules/yjs',
  },
```
which I think makes jest always load yjs from the same place (maybe from Jest's cache?)

**Comment by gplasky** [comment]
I, too, am running into this issue while trying to run Jest against a Typescript codebase which has numerous direct and transitive dependencies on yjs (Jupyter Lab extension).  I don't have this issue when building and running the extension directly, so it feels like this is some sort of jest-related issue. I tried @culli's suggestion above to no avail.

The traceback I get from the failing test shows the yjs dependency about 5 packages down (@jupyterlab/notebook --> @jupyterlab/cells --> @jupyter/ydoc --> y-protocols --> yjs)
```
      at Object.<anonymous> (node_modules/yjs/src/index.js:124:11)
      at Object.<anonymous> (node_modules/y-protocols/dist/awareness.cjs:9:1)
      at Object.require (node_modules/@jupyter/ydoc/src/ydocument.ts:8:1)
      at Object.require (node_modules/@jupyter/ydoc/src/index.ts:15:1)
      at Object.require (node_modules/@jupyterlab/cells/src/model.ts:20:1)
      at Object.require (node_modules/@jupyterlab/cells/src/index.ts:14:1)
      at Object.require (node_modules/@jupyterlab/notebook/src/actions.tsx:11:1)
      at Object.require (node_modules/@jupyterlab/notebook/src/index.ts:8:1)
```

So far as I can tell there is no reason a different yjs version should be imported here as there are no version conflicts in my `yarn.lock`/`package-lock.json` that would otherwise require reimporting of a conflicting yjs version.

**Comment by davisg123** [comment]
For jest we fixed this by stubbing the module in `setup.ts`

```
jest.mock('yjs');
```

and selectively including it in the tests that make use of yjs:
```
jest.mock('yjs', () => ({
  ...jest.requireActual('yjs'),
}));
```

**Comment by santanubasu** [comment]
Copying this here from a post I made on https://discuss.yjs.dev/t/multiple-import-of-yjs-warning-with-a-twist/2422:

-----

For posterity, here's what worked in my specific case.  I was using rollup and yjs was a dependency at multiple levels of my dependency tree, even within my own source.  However, I hadn't listed yjs as an external in the rollup config.  It was getting bundled in multiple times, all accessed via esm import, but with referentially distinct (and version equal) instances of the yjs constructor.  With external yjs my top level application provided the single instance to be used everywhere.

rollup config (to be used at all dependency levels except topmost):
```
export default {
    input: '...',
    external: ['yjs'],
    output: [
        ...
    ],
    plugins:[
        ...
    ]
}
```

Hope this can help someone

**Comment by andrioid** [comment]
I'm trying to get React Native (Expo SDK 50) working with YJS and this meets me out of the gate. This may be because the Metro dev server is doing both. If anyone has a work-around for Expo, that would be great.

**Comment by killjin** [comment]
```
import { fileURLToPath } from 'url';
import { dirname } from 'path';
import { createRequire } from 'module';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const require = createRequire(import.meta.url);
const path = require('path');

webpack: (config, { buildId, dev, isServer, defaultLoaders, webpack }) => {
    config.resolve.alias["yjs"] = path.resolve(__dirname, "node_modules/yjs")
    return config
  },
````

add this in next.config.mjs

**Comment by johntdowney** [comment]
I have multiple projects with common libraries.

For webpack, what resolved this (and a whole lot of other similar conflicts with different libraries) for me was something like...

#### parent package's webpack configuration:

```json
  resolve: {
    alias: {
      yjs: path.resolve(__dirname, '../node_modules/yjs'),
    }
  }
```

#### imported package's webpack configuration:
```json
   externals: {
     yjs: 'yjs'
   }
```

Make sure you get the alias right and, in your common package, mark it in `externals`.

**Comment by doodlewind** [comment]
For node users, this error happens when you import CommonJS yjs dependencies from ESM. Example:

``` js
import * as Y from 'yjs'
// CommonJS dependency
import { setupWSConnection } from 'y-websocket/bin/utils'
```

The CommonJS file has to be converted into ESM to fix this issue.

**Comment by acenturyandabit** [comment]
I got this error with this setup:

```bash
ROOT=/path/to/wherever
# Create a module "module1" with yjs as a dependency
mkdir $ROOT/module1 && cd $ROOT/module1 && npm init && npm install yjs
# Add a file in module1 that imports yjs
cat << EOF > module1Import.ts
import * as Y from "yjs";
export const someFunctionThatUsesYForTypeHint = (doc: Y.Doc)=>{
    // do whatever
}
EOF

# Create an app "main" with yjs also as a dependency, and module1 as a dependency
mkdir $ROOT/module2 && cd $ROOT/module2 && npm init && npm install yjs tsx && npm install ../module1

cat << EOF > main.ts
import * as Y from "yjs";
import {someFunctionThatUsesYForTypeHint} from "module1/module1Import.ts"
export const main = () => {
    const doc = new Y.Doc();
    someFunctionThatUsesYForTypeHint(doc);
}
EOF

# Try to run

tsx main.ts
```
This results in an error:
```
Yjs was already imported. This breaks constructor checks and will lead to issues! - https://github.com/yjs/yjs/issues/438
```

**Comment by acenturyandabit** [comment]
I had further issues: I was using `y-indexeddb` in `main`, which conflicted with the `y-websocket` in `module1`. The solution was to move `y-indexeddb` to `module1`:

```bash
cd $ROOT/main && npm uninstall y-indexeddb

cd $ROOT/module1 && npm install y-indexeddb
# Create a file in module1 that just exports y-indexeddb
cat << EOF > indexedDB.ts
import * as YindexedDB from "y-indexeddb";
export default YindexedDB;
EOF
```
```ts
// Then in main.ts, replace:
import { IndexeddbPersistence } from 'y-indexeddb'
const indexedDBPersistence = new IndexeddbPersistence(...)
// with
import YindexedDB from "common/indexedDB";
const indexedDBPersistence = new YindexedDB.IndexeddbPersistence (...)
```

**Comment by acenturyandabit** [comment]
You can also replace any `import * as Y from "yjs"` with `import type * as Y from "yjs";` for type declarations; or use a similar trick to re-export `Y` from `module1` if you need to use other features of `Y`, like the UndoManager.

**Comment by Jkense** [comment]
> [ryantan](/ryantan)

This solution did not work for me, I keep seeing the error. I also have issues with the editor `Error: Unexpected content type in insert operation`, although this might be unrelated.

**Comment by Jkense** [comment]
The solution that worked for my nextjs app was to modify `next.config.js

```
const path = require('path');

module.exports = {
  webpack: (config, { isServer }) => {
    if (!isServer) {
      // Ensure that all imports of 'yjs' resolve to the same instance
      config.resolve.alias['yjs'] = path.resolve(__dirname, 'node_modules/yjs');
    }
    return config;
  },
};
```

**Comment by zakwear** [comment]
My next project didn't respond to the webpack config, but setting this suppressed the warning:

`  experimental: {
      serverComponentsExternalPackages: ["yjs"]
   },`

**Comment by rizrmd** [comment]
this error shows when I ran `bun run --hot server.ts`, since yjs will be re-imported each time file changes.

**Comment by MetaMmodern** [comment]
Solution by @zakwear was not enough for me. I have a Nextjs app with App router and custom server(running with tsx), using `y-websocket` as a dependency as well, importing `bin/utils`. Here, without any additional configuration and trying to use ESM Yjs is possibly being imported in these cases (red ones are what breaks):
- ✅ potentially inside express server directly (ESM)
- 🔴 inside express server through y-websocket (I imported ESM, file does a CJS require call)
- ✅ inside nextjs server component `page.tsx` directly (ESM)
- 🔴 inside nextjs server component `page.tsx` through y-websocket (I imported ESM, file does a CJS require call)
- 🔴 inside nextjs client component pre-rendering on server (ESM)
- ✅ inside nextjs client component on client side (ESM)

Important note here is that even though sometimes we referred to module as ESM we still have issue, cause the module gets bundled becoming a completely different module than what express server is using.

In order to fix most of issues I had to:
1. Switch everything to CJS on my express server.
2. Tell Nextjs to treat `"yjs"` as external dependency on server-side, so that it doesn't get bundled into a module.
3. Tell webpack to use yjs.cjs when using yjs on server.

First is easy.
Second is achieved by adding this to nextconfig: `experimental: { serverComponentsExternalPackages: ["yjs"] }, `
Third is achieved by adding this:
```js
webpack: (config, { isServer }) => {
    if (isServer) {
      // Resolve path to CJS file explicitly
      const yjsEsmPath = path.resolve(
        fileURLToPath(import.meta.url), //weird, unnecessary, but I don't care
        "../node_modules/yjs/dist/yjs.cjs"
      );

      config.resolve.alias.yjs = yjsEsmPath;
    }
    return config;
  },
```

With these "patches" we get success on following:
- ✅ potentially inside express server directly (~~ESM~~ switch to CJS `require('yjs')`)
- ✅ inside express server through y-websocket (~~I imported ESM, file does a CJS require call~~ I switch to CJS)
- ✅ inside nextjs server component `page.tsx` directly (keep ESM, wepback will take care of it)
- ✅ inside nextjs server component `page.tsx` through y-websocket (~~I imported ESM, file does a CJS require call~~ I switched to CJS)
- 🔴 inside nextjs client component pre-rendering on server (keep ESM, wepback not taking care of it)
- ✅ inside nextjs client component on client side (keep ESM)

So, the only problematic part left is when you import yjs as ESM in a component, and you know it's not gonna be used in server, but it's been rendered there anyway. I think it has 0 impact on operability of server-side stuff, and on client side it's all ESM anyway.
I'll be ignoring this log for now for client component. I don't want to switch to CJS for client cause I want to keep tree-shakeability.

It's a lot to fit in head simultaneously, so sorry if you see misalignments, but hope this helps others. Rule of thumb: try to force only one type of module in a single environment(mostly CJS on server), you're okay having different modules in different environments (All CJS on server, allowed ESM in client side).

**Comment by pwFoo** [comment]
Hey, 
tried with browser modules from jsdelivr and get the same error.
Imported yjs and y-webrtc once. Looks like y-webrtc imports yjs twice? y-webrtc bug? 
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Yjs</title>
</head>
<body>
  <h1>Yjs Demo</h1>
  <textarea id="editor"></textarea>

  <script type="module">
    import * as Y from '//cdn.jsdelivr.net/npm/yjs@latest/+esm'
    import { WebrtcProvider } from '//cdn.jsdelivr.net/npm/y-webrtc@latest/+esm'

    const doc =  new Y.Doc()
    const yText = doc.getText('shared-text')

    // WebRTC Provider (verbindet automatisch mit anderen Peers im selben Raum)
    const provider = new WebrtcProvider('atomdb', doc, { signaling: ['//signaling.it-dengler.de'] })

    const textarea = document.getElementById('editor')

    // Sync Y.Text mit dem Textfeld
    yText.observe(event => {
      textarea.value = yText.toString()
    })

    textarea.addEventListener('change', () => {
      yText.delete(0, yText.length)
      yText.insert(0, textarea.value)
    })

    window.replace = val => {
        yText.delete(0, yText.length)
        yText.insert(0, val)
    }
  </script>
</body>
</html>
```

**Comment by dmonad** [comment]
I'm not a fan of these CDN solutions. They make no effort at all to deduplicate imports.
Maybe try esm.sh

**Comment by jelf-pagepeek** [comment]
> this error shows when I ran `bun run --hot server.ts`, since yjs will be re-imported each time file changes.

@rizrmd Did you resolve this?

**Comment by rizrmd** [comment]
No, I just don't use yjs anymore.

**Comment by bburns** [comment]
Here's one solution.

I'd been using yjs and y-webrtc in the browser from a CDN for a week or two, then noticed that warning in the console. This gives it - 
 
```html
<script type="module">
  import * as Y from 'https://esm.sh/yjs@13.6.26'
  import { WebrtcProvider } from 'https://esm.sh/y-webrtc@10.3.0'
</script>
```

But y-webrtc uses yjs version ^13.6.8, which gets updated to the latest minor/patch version, which became 13.6.27 recently. 

So just use the same version signifier for yjs in the import -

```html
<script type="module">
  import * as Y from 'https://esm.sh/yjs@^13.6.8'
  import { WebrtcProvider } from 'https://esm.sh/y-webrtc@10.3.0'
</script>
```

No more warning!

**Comment by bburns** [comment]
> @rozek: first of all: would it be possible to `alert` this situation when running in a browser - since not everybody may look into the console all the time? You may even explicitly crash the app, which would should still be better than behaving in an unpredictable way, perhaps even damaging some data...

Yeah, I think stopping the app would be better than potentially corrupting data. 

It's pretty common to pin libraries at some version - I haven't come across a situation where doing so can lead to problems, as with yjs + y-webrtc etc. 

I don't think a warning in the console is enough, because your app can be running fine, then at some point yjs gets updated and it can break behind the scenes, despite your pinning the versions.

**Comment by dmonad** [comment]
@bburns it shouldn't be necessary to pinpoint versions. You can use esm.sh/yjs@^13 and esm.sh/y-webrtc@^10 to get the latest stable release. Do the same with other Yjs libraries to avoid issues with peer-dependencies.

**Comment by dmonad** [comment]
I'd be open to add a section in the README about how to import using CDNs. 

I can't just stop the app when Yjs is imported twice. There are cases when this warning can be ignored. A lot of users use different Yjs imports for different parts of their app (not a fan of it either). A more valid reason are live-reloads.

**Comment by bburns** [comment]
Okay, yeah that would be helpful. I guess the same would happen if you pinned the versions in node. Maybe you could mention it in the first post here also?

Thanks man! I appreciate the libraries - I'm using them for a personal project that idk if will ever see the light of day, synchronizing notes between browsers.

**Comment by shyam-habarakada** [comment]
@evanw thak you for your explanation & solution *[here](https://github.com/yjs/yjs/issues/438#issuecomment-1368468914)* 

My Claude code (using sonnet 5) threw its arms up with and _"I'm blocked and need help figuring this out"_ message at me when it ran into this issue. It did have some idea, from testing, that this was a module load issue, but was hesitant to go fiddle/hack with the loader's internal mechanisms and was preferring to go other routes. More importantly, it did not think to follow the link to this github issue which was thre in plain sight with the loader warning.

When I read through this and found your post, I gave it back to Claude, and here was its response. I thought you'd get a chuckle out of this 😄 

<img width="666" height="383" alt="Image" src="https://github.com/user-attachments/assets/3beb9b01-f9ef-4fbc-8b1a-08840940e747" />


EDIT: After a number of ways to solve this and rejecting a few patches that had been proposed, the AI found that the _real_ root cause was the repo's root package.json not having a "type" field set (defaulting to CommonJS). We verified setting "type": "module" at the project root, solves this issue cleanly (no longer any confusion about CJS vs ESM). This worked in production builds as well as dev builds, and this project also has next.js. fwiw.

Thanks and HTH.
