### ISSUE TITLE
Dropped support for Node 14 in patch release?

### ISSUE THREAD

**Issue by ryanb** [yjs/yjs#513]
It appears the latest version of yjs (13.5.51) doesn't support Node 14. Just confirming, is this intentional?

I'm surprised this is done in a patch release instead of a major/minor verison update.

**Comment by dmonad** [comment]
Hi @ryanb,

I introduced better random number generation in `lib0` (based on webcrypto), but accidentally removed support for node v14. When I found out I introduced the engine field and set it to node >= 16. In a way 13.5.51 only introduced a warning. I screwed up when upgrading `lib0`. I'm sorry for that.

I'm not sure if I should roll back `lib0` and maintain two versions (a legacy version and a more modern version that also supports deno & bun). Node v14 is no longer supported by the Node team and won't receive security updates starting next month.  So I'm not sure if it's even worth going through the trouble. In any case, I'm sorry for breaking compatibility.

I want to keep this issue open. If you can upgrade to node v18 (current LTS) that would be great. If not, please leave a comment here. If there is enough feedback I'm going to release a patch and keep maintaining node v14 for some more time.

**Comment by ryanb** [comment]
@dmonad thanks for the details. I'll work on upgrading our node, it's overdue. 😄

As you mentioned since Node 14 won't event receive security updates soon, I don't see a reason to continue supporting it.

**Comment by frelars** [comment]
Same issue and sadly stuck on 14 for now. Support for 14 would be nice :)

**Comment by esparkman** [comment]
I can second @frelars. We currently employee yjs in one of our products. We are stuck with Node 14 for at least the remainder of this Fiscal Year. @dmonad I'd love to chat more with you on potential options for reverting support for Node 14.

Thanks!

**Comment by franksiao** [comment]
@dmonad I'm from the same company as @esparkman and would like to give some context to our situation.

We are using YJS for the data model in our react app. A page can have any number of Prosemirror/Tiptap components that are `Y.XmlFragment`s wrapped in our document. We are using it for all text inputs and paragraphs on the page. 

We are started to run into the [cleanupTransactions causes "maximum call stack size exceeded"](https://github.com/yjs/yjs/issues/522) issue. It was caused by us calling `toJSON` on the `YMap` wrapper for all the `XmlFragment`s which we use to render the page in react. As you have stated [here](https://github.com/yjs/yjs/issues/506#issuecomment-1462011540), each call to `toJSON` will "generate one cleanup transaction for every single Y.XmlText object." Would you advise us to avoid using `toJSON` in this way?

Also, it would be great if you can release a patch to continue to support node 14. Thank you so much for your work on this project.

**Comment by dmonad** [comment]
@franksiao Off-topic: Just update the Yjs package. The issue is already fixed :wink: 

On-topic: It would be a HUGE amount of work for me to maintain two lib0 packages. It seems rather simple to switch to a current node version. Please understand that I'm not very enthusiastic to jump to the occasion.

**Comment by franksiao** [comment]
@dmonad Sorry, I initially thought the [bug fix](https://github.com/yjs/yjs/commit/227018f5c77b67967f67810ade40cbb190cbc2c8) we needed came after the node version bump. I just updated YJS to 13.5.50 problem is fixed. Thanks! 

But as @esparkman stated before, our company will not be able to upgrade node for a while so we won't be able to pull in any newer features/fixes after 13.5.51. 

Maybe I'm misunderstanding the situation but why do you have to maintain two lib0 packages if you downgrade to supporting node 14 in YJS?  The most recent lib0 version [supports >= 14](https://github.com/dmonad/lib0/blob/main/package.json#L483-L485).

**Comment by dmonad** [comment]
> Maybe I'm misunderstanding the situation but why do you have to maintain two lib0 packages if you downgrade to supporting node 14 in YJS? The most recent lib0 version [supports >= 14](https://github.com/dmonad/lib0/blob/main/package.json#L483-L485).

Please have a look at my first answer above.

> On-topic: It would be a HUGE amount of work for me to maintain two lib0 packages. It seems rather simple to switch to a current node version. Please understand that I'm not very enthusiastic to jump to the occasion.

To be more explicit (if I didn't make that clear earlier) I don't care about supporting deprecated Nodejs releases forever. You can't expect me to do that simply out of the goodness of my heart. I'm running a current nodejs version that receives security patches and maybe your company should too. Please use your company's resources to investigate this issue and come up with a solution. I don't want to discuss further in this ticket. You can probably devise a solution and make a PR to `lib0` that fixes this issue.
