### ISSUE TITLE
earlier changes on disconnected device overwrite later changes made elsewhere upon reconnect

### ISSUE THREAD

**Issue by rozek** [yjs/yjs#520]
(Note: if this behaviour is not considered a "bug", it should be documented somewhere)

I'm currently experimenting with the behaviour of Yjs in case of network fragmentation.

My scenario:

* Yjs with y-websocket (but without y-indexeddb), data ist stored in a single y-keyvalue entry
* one mobile client (this one will get disconnected later)
* two desktop clients (always connected to a y-websocket server)

My procedure:

1. all clients get connected to the same y-webserver and synchronized to an initial state "A"
2. the mobile client gets disconnected (Wifi is switched off)
3. on the mobile client, a change is made ("A-B")
4. one minute later, on a desktop client, a different change is made ("A-C") and sync'ed to the other desktop client. Note: the mobile client is still disconnected
5. the mobile client gets connected again (Wifi is switched on)

Expected behaviour:

* mobile client should be sync'ed to "A-C"

Actual behaviour:

* desktop clients get sync'ed to "A-B"

How can I achieve a policy, where later changes will override earlier ones? (otherwise, the state of a data set would be highly dependent on the network history - which is a definite no-go)

**Comment by dmonad** [comment]
Hi @rozek,

This is a common misunderstanding.

Systems for conflict resolution should not rely on time (as in "wall clock time").  First of all, time is not synced between devices. Secondly, who is to say that the changes from the desktop client should supersede the changes from the mobile client just because they happened "later" (however you wanna measure this)? The changes were concurrent. Yjs is the arbiter that decides how to resolve conflicts.

Automatic conflict resolution can never be perfect and do exactly what you intended (i.e. understand the semantics of your application/data structure and perform the perfect merge). If you don't want changes to merge (e.g. because the changes were stale on an offline computer for over a week, or because they don't fit anymore), then you can make that change to the network provider (discard the current document). Or you provide a UI to check the changes before committing them to others.

Regarding persistence: y-indexeddb does not add temporal ordering. Who "wins" is decided by the `ydoc.clientID` (important: don't mess with the `clientID`). From your point of view, it is random.
