### ISSUE TITLE
Allow some origins to propagate

### ISSUE THREAD

**Issue by davidbrochart** [yjs/yjs#659]
Currently origins are only local, they don't propagate e.g. through the network. It seems fair since an origin can be an arbitrary object. But I was wondering if it could be possible to propagate origins of a restricted type, for instance string or integer origins?

**Comment by dmonad** [comment]
That would be a breaking change and it would require a change of the Yjs encoding.

Origins indicate which component triggered a Yjs transaction. It can be used to avoid infinite loops. E.g.

The user types a character 

1. Codemirror emits an event that a character was inserted 
2) y-codemirror picks up the change and reflects it in the ytext type using the origin "ycodemirror"
3) the ytext event listener in y-codemirror receives an event indicating a character was inserted. If the transaction event is not "ycodemirror", reflect the change in the codemirror editor.

Without the origin, we would transition from step 3 to step 1 -> causing an infinite loop.

Since "double bindings" are a major use case for Yjs, I integrated the origin concept.

If origins were global (across network) all editor bindings would stop working as we would never transition from step 3.

If a change comes from a remote peer, the origin should be the instance of the provider that received the change. This is how it was intended. Similar to editor bindings, we also want to avoid infinite loops when receiving/emitting changes.
