### ISSUE TITLE
Test failed: error TS2694: Namespace ‘LinkifyIt’ has no exported member ‘LinkifyIt’ 

### ISSUE THREAD

**Issue by drriguz** [yjs/yjs#662]
> Please save me some time and use the following template. In 90% of all issues I can't reproduce the problem because I don't know what exactly you are doing, in which environment, or which y-* version is responsible. Just use the following template even if you think the problem is obvious.

**Checklist**

* [x] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [ ] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**
`yarn test` failed

**To Reproduce**
1. Create a fresh node environment `docker run -it node:18 bash`
2. Clone the yjs source code `git clone https://github.com/yjs/yjs.git`
3. Install dependencies `cd yjs && yarn`
4. Run tests via `yarn test`, and then the error occurs:
```
created dist/tests.cjs in 565ms
node_modules/@types/markdown-it/lib/index.d.ts:151:33 - error TS2694: Namespace 'LinkifyIt' has no exported member 'LinkifyIt'.

151     readonly linkify: LinkifyIt.LinkifyIt;
                                    ~~~~~~~~~


Found 1 error in node_modules/@types/markdown-it/lib/index.d.ts:151

npm notice
npm notice New minor version of npm available! 10.7.0 -> 10.8.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.8.2
npm notice To update run: npm install -g npm@10.8.2
npm notice
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Expected behavior**
Tests should pass without error.

**Screenshots**
![image](https://github.com/user-attachments/assets/d163fb0e-9700-46b6-b2e4-6b202e53b697)

**Environment Information**
- NodeJs 18.20.4
- Yjs master

**Additional context**
I tried both NodeJs 20 and 18, and got same error.

* [ ] I'm a sponsor 💖
* [ ] This issue is a blocker for my project.

**Comment by drriguz** [comment]
A similar issue has been reported here: https://github.com/markdown-it/linkify-it/issues/111
And here's the workaroud:

```
npm i @types/linkify-it@3.0.5
```

**Comment by dmonad** [comment]
You should be able to use `yarn` in your own projects. If you ever encounter an issue with Yjs<>yarn, please let me know.

Yarn and npm both maintain a `package.lock` and `yarn.lock` file to force all users to install the same versions of dependencies. This ensures that if it works on my system, it will work on your system as well.

This is a huge achievement because new versions of dependencies tend to break systems once in a while. If everyone installs the same versions, we run into less unpredictable errors.

Since Yjs maintains a `package.lock` file, please use a compatible package manager (e.g. `npm`) to install dependencies.

Supporting `yarn` for the development build is out of scope for this project.

I just bumped markdownlint to the latest version, this might fix your issue. However, I still encourage you to use `npm` if you encounter `package.lock` files in other projects.

**Comment by drriguz** [comment]
> You should be able to use `yarn` in your own projects. If you ever encounter an issue with Yjs<>yarn, please let me know.
> 
> Npm maintains a `package.lock` file and yarn a `yarn.lock` file, respectively, to force all users to install the same versions of dependencies. This ensures that if this project runs on my system, it will work on your system as well.
> 
> This is a huge achievement because new versions of dependencies tend to break systems once in a while. If everyone installs the same versions, we run into less unpredictable errors. Hence both npm and yarn use this feature by default. But they have different resolution algorithms that are incompatible - hence different files.
> 
> Since Yjs maintains a `package.lock` file, please use a compatible package manager (e.g. `npm`) to install dependencies.
> 
> Supporting `yarn` for the development build is out of scope for this project.
> 
> I just bumped markdownlint to the latest version, this might fix your issue. However, I still encourage you to use `npm` if you encounter `package.lock` files in other projects.

Aha, I got it. Npm works fine.
