### ISSUE TITLE
[IDEA] Consider using MoonBit to make Yjs more performant

### ISSUE THREAD

**Issue by mindreframer** [yjs/yjs#683]
Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
---
## [FORUM] password reset on the forum not working

I cant login to discuss.yjs.dev via Github, it throws a 500 error. Resetting password also is not working, not sure why... 

<img width="1440" alt="Screenshot 2024-12-24 at 11 44 57" src="https://github.com/user-attachments/assets/9386b8a7-c828-492d-94cd-ca42b144f560" />

--- 
## [IDEA] Consider using MoonBit to make Yjs more performant. 
Thats why I will post this idea here.  First of all - thanks for all the amazing work on Yjs @dmonad! 10 years is crazy long, and Yjs became de-facto the standard CRDT for many apps. I have watched your talk from the Local-first meetup and was surprised to hear that you are possibly considering WAST to re-implement Yjs. - https://www.youtube.com/watch?v=wjUfqFWpI2k 

Maybe there is a more dev-friendly alternative for this. 
Have you tried MoonBit - https://thenewstack.io/moonbit-wasm-optimized-language-creates-less-code-than-rust/? 

I have played with it recently and was blown away by the developers ergonomics! It brings all the things to the table to build highly-performant CRDT algorithms. WASM first, extremely fast compilation times, rust-inspired type system, go inspired packaging system, very small generated WASM files, very robust IDE integration. It seems to be an interesting and promising mix of pragmatic decisions, that makes using MoonBit a great experience. 

Some links
- https://www.moonbitlang.com/
- https://mooncakes.io/ (existing packages)
- compiler - https://github.com/moonbitlang/moonbit-compiler
- Future website - https://www.moonbitlang.com/next-index/
- Book - https://moonbitlang.github.io/moonbit-textbook/
- Lang tour - https://tour.moonbitlang.com/index.html
- Youtube - https://www.youtube.com/@MoonBit_lang/videos
- Testing - https://www.moonbitlang.com/blog/expect-testing

Interesting projects
- https://github.com/moonbit-community/cmark/ (tests compile and finish in milliseconds)

So yeah, maybe this suggestion will put MoonBit on your personal "tech" radar. Who knows. 

And sorry that I post it here, password reset is not working on YJS discourse, not sure what I can do to fix it.

**Comment by dmonad** [comment]
Hi @mindreframer ,

looks really interesting!

I also took a look at [AssemblyScript](https://www.assemblyscript.org/). But I like the control that WAST gives me. For example, it enables me to work with object references directly.  I can also use the latest WAST features.

As I said in the talk, I probably don't want to rewrite _everything_. Building custom data structures for storing CRDT operations, would give me a huge performance boost. I want to keep the rest in JavaScript, because it provides a better debugging experience (for me, and also for the users of Yjs).

But I will definitely look out for MoonBit development, it looks pretty interesting!

---

Could you please try again to reset your password? You might have done so during a software upgrade. If it still doesn't work, I can reset your password directly (ping me directly, so I can send you a temp password).

**Comment by mindreframer** [comment]
@dmonad Interesting! I will look out for the results, especially the combo of datastructures in WASM and the rest in JS, this option did not occur to me. 

Password reset: still not working. I will ping you via email. Thanks and have a good friday!
